import "server-only";
import { prisma } from "@/lib/prisma";

/**
 * RemindersDB
 *
 * Audit project-wide 2026-05-19 — migracion de /api/reminders.
 * tenantId obligatorio (CLAUDE.md #3).
 */

export interface ReminderRow {
  id: string;
  tenantId: string;
  title: string;
  description: string;
  type: string;
  priority: string;
  status: string;
  dueDate: Date;
  autoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const RemindersDB = {
  async list(tenantId: string): Promise<ReminderRow[]> {
    return prisma.reminder.findMany({
      where: { tenantId },
      orderBy: [{ status: "asc" }, { dueDate: "asc" }],
    });
  },

  /**
   * Marca como "vencido" todos los reminders pendientes con dueDate
   * pasado. Idempotente — solo updatea los que aun estan en pendiente.
   */
  async markOverdue(tenantId: string): Promise<void> {
    await prisma.reminder.updateMany({
      where: {
        tenantId,
        status: "pendiente",
        dueDate: { lt: new Date() },
      },
      data: { status: "vencido" },
    });
  },

  async create(
    tenantId: string,
    data: {
      title: string;
      description: string;
      type: string;
      priority: string;
      dueDate: string;
      autoGenerated: boolean;
    },
  ): Promise<ReminderRow> {
    return prisma.reminder.create({
      data: {
        ...data,
        dueDate: new Date(data.dueDate),
        tenantId,
      },
    });
  },

  async updateForTenant(
    tenantId: string,
    id: string,
    data: Partial<{
      title: string;
      description: string;
      type: string;
      priority: string;
      status: string;
      dueDate: string;
    }>,
  ): Promise<ReminderRow | null> {
    const existing = await prisma.reminder.findFirst({
      where: { id, tenantId },
      select: { id: true },
    });
    if (!existing) return null;
    const { dueDate, ...rest } = data;
    return prisma.reminder.update({
      where: { id },
      data: { ...rest, ...(dueDate && { dueDate: new Date(dueDate) }) },
    });
  },

  async deleteForTenant(tenantId: string, id: string): Promise<boolean> {
    const existing = await prisma.reminder.findFirst({
      where: { id, tenantId },
      select: { id: true },
    });
    if (!existing) return false;
    await prisma.reminder.delete({ where: { id } });
    return true;
  },
};
