ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "resolucion" TEXT;
ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "planManejo" TEXT;
ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "arffs" TEXT;
ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "representante" TEXT;
ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "logo" TEXT;
ALTER TABLE "ForestParty" ADD COLUMN IF NOT EXISTS "adjuntos" JSONB;
