/**
 * @buleje/design-system/icons — Re-export canónico de lucide-react.
 *
 * REGLA: Toda importación de íconos en `components/admin/**` y `app/admin/**`
 * debe pasar por este archivo. El linter lo fuerza.
 *
 * Beneficios:
 *   - Tree-shake: named exports → bundler elimina lo no usado.
 *   - Fuente única: rebranding de ícono = 1 cambio aquí.
 *   - Governance: el set de íconos admitidos es finito y revisable.
 *
 * Si necesitás un ícono que no está aquí, agregalo en este archivo (sin
 * sinónimos redundantes, preferí el nombre original de lucide).
 *
 * @example
 * import { ShoppingCart, Package, Heart } from "@buleje/design-system/icons";
 */

export {
  // ── Nav / layout ─────────────────────────────────────────────
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  ChevronsLeft,
  ChevronsRight,
  Menu,
  X,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowDownUp,
  ArrowUpDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpFromLine,
  ArrowDownToLine,
  Home,
  PanelLeftClose,
  PanelLeftOpen,
  MoreVertical,
  MoreHorizontal,
  ExternalLink,

  // ── People & account ─────────────────────────────────────────
  User,
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  LogIn,
  LogOut,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Key,

  // ── Commerce ─────────────────────────────────────────────────
  Store,
  ShoppingCart,
  ShoppingBag,
  Package,
  PackagePlus,
  PackageCheck,
  PackageOpen,
  Tag,
  Tags,
  Gift,
  Truck,
  Warehouse,
  Receipt,
  FileText,
  FileSpreadsheet,
  FileBarChart,
  BadgePercent,
  Percent,

  // ── Money ────────────────────────────────────────────────────
  Wallet,
  DollarSign,
  CreditCard,
  Banknote,
  HandCoins,
  Landmark,
  Coins,
  PiggyBank,

  // ── Charts / analytics ───────────────────────────────────────
  BarChart,
  BarChart3,
  LineChart,
  PieChart,
  Activity,
  TrendingUp,
  TrendingDown,
  Target,
  Gauge,

  // ── Status / feedback ────────────────────────────────────────
  CheckCircle2,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Bell,
  BellOff,
  BellRing,
  Loader2,
  Loader,
  RefreshCw,
  RotateCw,
  TimerReset,
  Clock,
  Clock3,
  Check,
  CircleDot,

  // ── Actions ──────────────────────────────────────────────────
  Plus,
  Minus,
  Edit,
  Edit2,
  Edit3,
  Pencil,
  Crop,
  Scissors,
  // Food/category fallback icons (audit P0 UX #2)
  Pizza,
  Beef,
  Beer,
  Carrot,
  ChefHat,
  Coffee,
  Cookie,
  Croissant,
  Drumstick,
  EggFried,
  Fish,
  Milk,
  Sandwich,
  Apple,
  Trash2,
  Trash,
  Download,
  Upload,
  Eye,
  EyeOff,
  Save,
  Copy,
  Share2,
  Send,
  Filter,
  SlidersHorizontal,
  Search,
  Settings,
  Settings2,
  Cog,

  // ── Contact / location ───────────────────────────────────────
  MapPin,
  Map,
  Locate,
  Phone,
  Mail,
  MessageSquare,
  MessageCircle,
  Calendar,
  CalendarDays,
  CalendarClock,

  // ── Organization / domain ────────────────────────────────────
  Building2,
  Building,
  Briefcase,
  ClipboardList,
  ClipboardCheck,
  Clipboard,
  Inbox,
  Box,
  Boxes,
  Layers,
  Combine,
  Stamp,
  Folder,
  FolderOpen,

  // ── Science / AI / industry ──────────────────────────────────
  FlaskConical,
  Brain,
  Sparkles,
  Zap,
  Bomb,
  Rows2,
  Rows3,
  Rows4,
  BotMessageSquare,
  Bot,
  Palette,
  // Formato de texto en el editor de planillas/documentos
  Bold,
  Italic,
  Underline,
  Sigma,
  Heart,
  HeartHandshake,

  // ── Text / rich content ──────────────────────────────────────
  Hash,
  Type,
  Link,
  Link2,
  Instagram,
  Facebook,
  Image,
  ImageIcon,

  // ── Misc ─────────────────────────────────────────────────────
  Star,
  Flag,
  Bookmark,
  ThumbsUp,
  ThumbsDown,
  HelpCircle,
  CircleHelp,
  Circle,
  Square,
  Triangle,
  Dot,

  // ── Extended set (post-migration) ───────────────────────────
  AlertOctagon,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Archive,
  ArrowDownCircle,
  ArrowUpCircle,
  Award,
  Ban,
  Barcode,
  Battery,
  Beaker,
  Bike,
  Car,
  Footprints,
  BookOpen,
  BookOpenText,
  BookTemplate,
  Calculator,
  Camera,
  CheckCheck,
  CheckSquare,
  CircleUser,
  CloudRain,
  Code2,
  Columns2,
  Columns3,
  Command,
  Cpu,
  Crown,
  Database,
  Droplets,
  Expand,
  FileCheck,
  FileDown,
  FileJson,
  FileMinus,
  FileSignature,
  FileUp,
  FileX,
  Flame,
  Flashlight,
  FlashlightOff,
  Flower2,
  Fuel,
  Gamepad2,
  GitCompareArrows,
  GitMerge,
  Globe,
  GraduationCap,
  Grid3X3,
  Grid3x3,
  GripVertical,
  GripHorizontal,
  HardDrive,
  HeartPulse,
  History,
  ImageOff,
  Kanban,
  KeyRound,
  Keyboard,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Leaf,
  Lightbulb,
  List,
  ListChecks,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  MemoryStick,
  Newspaper,
  MessageCircleQuestion,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  MinusCircle,
  Monitor,
  Moon,
  MousePointer,
  Navigation,
  NotebookPen,
  Paintbrush,
  Paperclip,
  PartyPopper,
  Pause,
  PenTool,
  Pin,
  PinOff,
  Play,
  PlusCircle,
  PlusSquare,
  Power,
  PowerOff,
  Printer,
  QrCode,
  Redo2,
  Repeat,
  Rocket,
  RotateCcw,
  Route,
  Scale,
  Scan,
  ScanBarcode,
  ScanLine,
  ScrollText,
  Server,
  Sliders,
  Smartphone,
  Smile,
  Snowflake,
  StarOff,
  Stethoscope,
  StickyNote,
  Sun,
  SunMoon,
  Sunrise,
  Sunset,
  SwitchCamera,
  Table,
  Tablet,
  Thermometer,
  Ticket,
  Timer,
  ToggleLeft,
  ToggleRight,
  TreePine,
  Trophy,
  Undo2,
  UserCircle,
  UserCog,
  UtensilsCrossed,
  Vibrate,
  Volume2,
  VolumeX,
  Wand2,
  Waves,
  Webhook,
  Wifi,
  WifiOff,
  Wind,
  Wrench,

  // ── Additional pass 2 (post-migration fixups) ────────────────
  ArrowLeftRight,
  ArrowRightLeft,
  BarChart2,
  BookmarkPlus,
  CalendarOff,
  ClipboardCopy,
  Compass,
  PackageX,
  Quote,
  Radio,
  RefreshCcw,
  ShieldOff,
  ShieldX,
  ShoppingBasket,
  Users2,
  WandSparkles,
  ZoomIn,
  ZoomOut,

  // ── Additional pass 3 (sitemap module ADR-??) ────────────────
  Cable,
  Code,
  Video,
  Trees,

  // ── Additional pass 4 (superadmin codemod 2026-05-19) ────────
  Construction,
  Eraser,
  Images,
  MailOpen,
  ReceiptText,

  // ── Additional pass 5 (marketplace category icons 2026-05-26) ──
  Wine,
  WineOff,
  Pill,

  // ── Additional pass 6 (recetario 2026-06-14) ──
  Utensils,
  Salad,
  Soup,
  Cake,
  GlassWater,
  SearchX,

  // ── Types ────────────────────────────────────────────────────
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

// Aliases semánticos re-exportados para uso claro en el dominio:
export { Zap as Lightning } from "lucide-react";
export { CreditCard as Card } from "lucide-react";
