/**
 * lib/roadmap/items.ts
 *
 * Master Roadmap 2026-04-09 — 84 improvements consolidated from 6 research scouts.
 *
 * Content is STATIC in code (edit here to add/modify items). Mutable status lives
 * in the RoadmapItemStatus table and is merged at read time.
 *
 * Source of truth: docs/research/MASTER-ROADMAP-2026-04-09.md
 *
 * Breakdown:
 *   - Tier S: 15 items (items 1-15) — 6 critical bugs + 9 high-impact deliveries
 *   - Tier A: 16 items (items 16-31) — strategic next wave
 *   - Tier B: 15 items (items 32-46) — complementary improvements
 *   - Tier C: 38 items (items 47-84) — backlog (prioritised)
 *
 * Regla: items 1-6 son bugs críticos (`isCriticalBug: true`) y se renderizan
 * en el hero destacado del módulo Roadmap del superadmin.
 */

export type RoadmapTier = "S" | "A" | "B" | "C";

export type RoadmapScope =
  | "marketplace"
  | "admin"
  | "superadmin"
  | "store"
  | "cross-cutting"
  | "product-ux";

export type RoadmapType = "fix" | "new" | "expansion" | "complete";

export type RoadmapEffort = "S" | "M" | "L" | "XL";

export type RoadmapPriority = "P0" | "P1" | "P2" | "P3";

export interface RoadmapItem {
  /** Stable slug identifier — used as foreign key in RoadmapItemStatus table */
  id: string;
  /** Display order (1..84) — matches Master Roadmap numbering */
  number: number;
  /** Short human title */
  title: string;
  /** 1-2 paragraph description (plain text, line breaks preserved) */
  description: string;
  tier: RoadmapTier;
  scope: RoadmapScope;
  type: RoadmapType;
  /** Short impact statement (one line) */
  impact: string;
  effort: RoadmapEffort;
  priority: RoadmapPriority;
  /** Research source file name (under docs/research/) */
  researchFile: string;
  /** Ids of items this one depends on */
  dependencies: string[];
  /** Marks the 6 critical bugs for the hero section */
  isCriticalBug: boolean;
}

// ────────────────────────────────────────────────────────────────────────────
// Catalogue (84 items)
// ────────────────────────────────────────────────────────────────────────────

export const ROADMAP_ITEMS: RoadmapItem[] = [
  // ─── TIER S — 15 items (1-15) ────────────────────────────────────────────
  {
    id: "fix-platform-settings-mrr",
    number: 1,
    title: "Fix PlatformSettings fake MRR",
    description:
      "PlatformSettings vive en localStorage del browser, no en DB. Además los precios de planes están hardcoded en DOS lugares con valores distintos (pro:49/business:149/enterprise:399 en analytics vs enterprise:499 en superadmin-types). Resultado: el MRR que reporta el dashboard está MENTIROSO — off-by-100 por cada tenant enterprise.\n\nArreglar: crear modelo PlatformSetting (key/value JSON) + DB class con cache 5min + helper getPlanPrice(plan) single source of truth. Migrar settings page de localStorage → DB.",
    tier: "S",
    scope: "superadmin",
    type: "fix",
    impact: "Dashboard reporta MRR real. Decisiones basadas en data, no mentira. Desbloquea billing real.",
    effort: "S",
    priority: "P0",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: true,
  },
  {
    id: "fix-tenants-fantasma-apply",
    number: 2,
    title: "Fix tenants fantasma en apply flow",
    description:
      "En app/api/marketplace/stores/apply/route.ts línea 64-70: tenantId = `store-${ownerPhone}` crea IDs falsos que no corresponden a ningún Tenant real. Order.tenantId nunca matchea → tiendas huérfanas que no reciben pedidos.\n\nArreglar: crear Tenant real con prisma.tenant.create(), guardar tenantId = tenant.id en Store, enviar link mágico de login al vendedor. Data cleanup: buscar stores con tenantId LIKE 'store-%' y merge con tenant real.",
    tier: "S",
    scope: "marketplace",
    type: "fix",
    impact: "Previene data corruption cada día. Tiendas nuevas entran sanas desde el apply flow.",
    effort: "S",
    priority: "P0",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: true,
  },
  {
    id: "rate-limit-upstash-distributed",
    number: 3,
    title: "Rate limit distribuido Upstash",
    description:
      "lib/middleware-utils.ts L58 usa Map en memoria. En Vercel Edge cada replica tiene su Map independiente → un atacante con 10 replicas bypass ×10 (60 req/min config = 600 req/min reales). Es un DoS explotable HOY.\n\nArreglar: migrar a Upstash Redis REST (edge-compatible). `npm i @upstash/ratelimit @upstash/redis`, sustituir checkRateLimit en middleware-utils.ts. API compatible con FactoryLimiter existente.",
    tier: "S",
    scope: "cross-cutting",
    type: "fix",
    impact: "Cierra vector de DoS real explotable hoy. 0.5 día de esfuerzo, protección crítica.",
    effort: "S",
    priority: "P0",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: true,
  },
  {
    id: "abandoned-cart-whatsapp-cliente",
    number: 4,
    title: "Abandoned cart → WhatsApp al cliente",
    description:
      "app/api/abandoned-cart/route.ts manda email al NOTIFY_EMAIL (admin), NO al cliente. Feature existe pero 0% recovery real — el cliente jamás recibe el WhatsApp que lo traería de vuelta.\n\nArreglar: si parsed.data.phone existe → enviar WhatsApp al cliente con link directo al carrito. Rate limit: máximo 1 mensaje cada 48h por número. Cooldown 22:00-08:00.",
    tier: "S",
    scope: "product-ux",
    type: "fix",
    impact: "Recovery 8-12% de carts = +S/300-420/mes/tenant. Benchmark Shopify: 10% median.",
    effort: "S",
    priority: "P0",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: true,
  },
  {
    id: "daily-briefing-whatsapp-dueno",
    number: 5,
    title: "Daily briefing WhatsApp al dueño",
    description:
      "Step 5 del onboarding promete 'te mandaremos resumen por WhatsApp' pero /api/daily-digest solo manda Email. Además retorna {sent:false} si no hay ventas — silencia al dueño en sus peores días.\n\nArreglar: sendDailyDigestWhatsApp(tenantId) en lib/mailer-digest.ts usando el conversation-engine. Enviar aunque no haya ventas ('Hoy no se registraron ventas. ¿Todo bien?').",
    tier: "S",
    scope: "product-ux",
    type: "fix",
    impact: "DAU admin +25%, feature adoption +300% (hoy 0%). Cumple la promesa del onboarding.",
    effort: "S",
    priority: "P0",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: true,
  },
  {
    id: "churn-engine-cron-playbook",
    number: 6,
    title: "Churn engine cron + playbook executor",
    description:
      "Schema TenantHealthScore + ChurnSignal + ChurnPlaybook ya existe (líneas 2756-2808) pero no hay motor corriendo. Dashboard de churn muestra datos vacíos/viejos, playbooks no ejecutan.\n\nImplementar: Vercel Cron diario 6am → computeTenantHealthScores() → detectChurnSignals() → executeChurnPlaybooks() con dispatch por action type (email/whatsapp/discount). Feature flag CHURN_AUTORUN para rollout gradual.",
    tier: "S",
    scope: "superadmin",
    type: "complete",
    impact: "-20-30% churn rate, retention directo. Schema ya existe, solo falta el motor.",
    effort: "M",
    priority: "P0",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["fix-platform-settings-mrr"],
    isCriticalBug: true,
  },
  {
    id: "crm-rfm-campanas-segmento",
    number: 7,
    title: "CRM + RFM integrado + campañas por segmento",
    description:
      "Hay DOS implementaciones de RFM que no se hablan: /api/customers/rfm (endpoint con 7 segmentos) y RFMSegmentationPanel (componente con 6 segmentos). Ninguna está cableada al CRMClientesModule que es donde el usuario realmente busca clientes.\n\nImplementar: agregar tab 'Segmentos RFM' en CRMClientesModule que consuma /api/customers/rfm + MassMessageSender preconfigurado con segmento. Unificar a una sola fuente.",
    tier: "S",
    scope: "admin",
    type: "complete",
    impact: "Duplica efectividad del CRM. Motor ya existe, solo cablear. 1 día de trabajo.",
    effort: "S",
    priority: "P0",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "checkout-multi-vendor-payout",
    number: 8,
    title: "Checkout multi-vendor + Payout cycle",
    description:
      "Sin esto el marketplace es catálogo agregado, no marketplace real. El carrito agrupa items por storeId pero POST /api/marketplace/orders crea un pedido por tienda sin checkout unificado ni split-payment. Además CommissionLedger solo inserta filas 'pending' — no hay payout cycle ni pago real a vendedores.\n\nImplementar: MarketplaceCheckoutSession { id, customerPhone, totalGross, platformFee }. PaymentIntent único con transfer_data/application_fee_amount por tienda. Cron semanal lunes 9am que calcula payouts + transfer via Stripe Connect + mark CommissionLedger settled.",
    tier: "S",
    scope: "marketplace",
    type: "new",
    impact: "Transforma marketplace en marketplace real. Rappi-model unlock. Sin esto, los bodegueros no se registran.",
    effort: "L",
    priority: "P0",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: ["fix-tenants-fantasma-apply"],
    isCriticalBug: false,
  },
  {
    id: "cupones-por-tienda-td032",
    number: 9,
    title: "Cupones por tienda (TD-032)",
    description:
      "Coupon no tiene storeId — los cupones son por tenant, no por tienda. El TODO está explícito en /api/marketplace/coupons/route.ts línea 41. Bloquea welcome coupons, flash sales por tienda, promos de apertura.\n\nImplementar: ALTER TABLE Coupon ADD COLUMN storeId. Index @@index([storeId, code]). UI vendor dashboard: toggle 'cupón de mi tienda' vs 'cupón de plataforma'. Backfill storeId=null para cupones actuales.",
    tier: "S",
    scope: "marketplace",
    type: "complete",
    impact: "Desbloquea welcome coupons, flash sales por tienda, promos de apertura de vendedores nuevos.",
    effort: "M",
    priority: "P0",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "catalogo-precargado-200-productos",
    number: 10,
    title: "Catálogo pre-cargado 200 productos peruanos",
    description:
      "El 80% de las bodegas venden los mismos 200 SKUs (Costeño, Gloria, Inka Cola, Don Vittorio, Pilsen Callao, Ace, Sapolio). La señora NO va a teclear 200 nombres — Vendemás y Loyverse ganan aquí.\n\nImplementar: seed estático JSON con 200+ productos peruanos típicos. Endpoint /api/onboarding/import-catalog. Paso nuevo en el wizard: '¿Qué vende tu bodega?' → multi-select de categorías → import masivo con precios sugeridos regionales.",
    tier: "S",
    scope: "product-ux",
    type: "new",
    impact: "Time-to-first-sale de 3 días → 20 min. Activation rate +40%.",
    effort: "M",
    priority: "P0",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "flujo-caja-13-semanas",
    number: 11,
    title: "Flujo de caja 13 semanas rodante",
    description:
      "Es el reporte #1 que pide cualquier dueño de bodega: '¿cuánto dinero voy a tener dentro de 2 semanas?'. Hoy CashFlowProjection.tsx proyecta solo 30 días sin incluir AR aging, payables reales ni nómina.\n\nImplementar: tabla 13 semanas × (Saldo inicial · Cobros esperados · Fiados a cobrar · Pagos proveedores · Nómina · Préstamos · Saldo final). Rojo si cae a negativo. Endpoint /api/finance/cashflow-rolling.",
    tier: "S",
    scope: "admin",
    type: "new",
    impact: "Anti-crisis de liquidez. Diferenciador #1 vs Loyverse/Alegra/Vendemás.",
    effort: "M",
    priority: "P0",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "fefo-enforcement-venta",
    number: 12,
    title: "FEFO enforceado en venta",
    description:
      "BatchesTab muestra vencimientos pero el POS no elige automáticamente el lote más cercano a vencer. En bodega con perecibles (lácteos, embutidos) genera S/200-500/mes de merma evitable.\n\nImplementar: modificar descuento de stock en lib/db/sales.db.ts → si producto tiene lotes, findMany ordered by expiryDate asc y descontar del primero con stock. Alerta en POS si lote vence < 7 días. Config por producto: forceFEFO true/false.",
    tier: "S",
    scope: "admin",
    type: "complete",
    impact: "Pérdida real S/200-500/mes evitable en perecibles.",
    effort: "M",
    priority: "P0",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "recetas-costo-real-stock",
    number: 13,
    title: "Recetas con costo real + descuento stock",
    description:
      "El módulo Recetas hoy es recetario 'bonito'. No calcula costo, no descuenta ingredientes, no da margen. Para una bodega que produce (jugos, sanguches, ceviche, desayunos) es el módulo más inútil del panel.\n\nImplementar: costoTotal = Σ(ingrediente.cantidad × producto.currentCost). Al registrar producción: InventoryMovement negativos por cada ingrediente + positivo por producto resultante. Margen: precioVenta - costoTotal / precioVenta * 100.",
    tier: "S",
    scope: "admin",
    type: "new",
    impact: "Módulo hoy 100% cosmético → operacional. Desbloquea bodegas con cocina.",
    effort: "M",
    priority: "P0",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "paridad-tienda-slug-buleje",
    number: 14,
    title: "Paridad /t/[slug]/tienda con Buleje",
    description:
      "app/(store)/** (Buleje, 500+ componentes) vs app/t/[slug]/tienda/page.tsx (413 líneas en un solo client component, sin categorías, sin checkout wizard). Los tenants SaaS hoy reciben experiencia degradada vs dogfood Buleje.\n\nImplementar: mover app/(store) a app/t/[slug] y hacer que Buleje use slug dedicado, con rewrite en proxy.ts para dominio raíz. Feature flag NEXT_PUBLIC_UNIFIED_STORE + rollout por tenant piloto. Requiere ADR nuevo.",
    tier: "S",
    scope: "store",
    type: "complete",
    impact: "Diferencia vida/muerte del producto SaaS. Conversión tenants +300-500%.",
    effort: "L",
    priority: "P0",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "self-signup-proveedor",
    number: 15,
    title: "Self-signup de proveedor",
    description:
      "app/supplier hoy solo pide API Key manual. Sin self-signup no hay escalamiento de supply side. Comparado con Rappi Turbo / Mercado Libre → cero adquisición orgánica de proveedores.\n\nImplementar: /supplier/registrar con formulario (RUC, categoría, productos). Backend crea Supplier pending_review. Brandon aprueba desde superadmin → genera API key y email al proveedor. Tab en /superadmin/marketplace/suppliers con queue de aprobación.",
    tier: "S",
    scope: "product-ux",
    type: "new",
    impact: "Desbloquea supply-side del marketplace. 0 → 5-20 proveedores/mes primer trimestre.",
    effort: "M",
    priority: "P0",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },

  // ─── TIER A — 16 items (16-31) ───────────────────────────────────────────
  {
    id: "billing-stripe-webhook-sync",
    number: 16,
    title: "Billing real Stripe webhook → Tenant sync",
    description:
      "Completar integración Stripe + Mercado Pago: cambios de plan → update real en Stripe. Webhooks (invoice.paid, customer.subscription.updated, invoice.payment_failed) escriben en BillingInvoice + sincronizan Tenant.stripeCurrentPeriodEnd. MRR calculado desde BillingInvoice real, no estimado.",
    tier: "A",
    scope: "superadmin",
    type: "new",
    impact: "+5x ARPU unlock (ADR 016). Detecta failed payments + dunning automático = +5-8% MRR recuperado.",
    effort: "L",
    priority: "P1",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["fix-platform-settings-mrr"],
    isCriticalBug: false,
  },
  {
    id: "wishlist-favoritos-cross-store",
    number: 17,
    title: "Wishlist + favoritos persistentes cross-store",
    description:
      "En CatalogView.tsx el <Heart /> solo guarda useState y se pierde al recargar. Convertirlo en wishlist real persistente por customerPhone. Modelo Favorite { customerPhone, storeProductId, productId, addedAt }. API POST/DELETE /api/marketplace/favorites. Cron que compara precios actuales vs precio al agregar → WhatsApp al bajar 10%+.",
    tier: "A",
    scope: "marketplace",
    type: "new",
    impact: "Retention +15%, remarketing via WhatsApp ('el producto X bajó de precio'), engagement +20%.",
    effort: "M",
    priority: "P1",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "kyc-vendedores-verificado",
    number: 18,
    title: "KYC básico de vendedores + badge Verificado",
    description:
      "Hoy cualquier persona puede registrar tienda con solo nombre + teléfono. Sin KYC no se puede hacer payout legal. Los compradores no confían en tiendas sin badge 'Verificada'. Schema: agregar a Store kycStatus, kycDniUrl, kycRucUrl, kycLocalPhotoUrl, kycVerifiedAt. Admin queue + badge en StoreCard.",
    tier: "A",
    scope: "marketplace",
    type: "new",
    impact: "Confianza +30% compradores, habilita payouts legales, compliance SUNAT/SBS.",
    effort: "M",
    priority: "P1",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: ["checkout-multi-vendor-payout"],
    isCriticalBug: false,
  },
  {
    id: "churn-b2c-cliente-final",
    number: 19,
    title: "Churn B2C por cliente final",
    description:
      "lib/churn/health-scorer.ts mide churn B2B (tenants). No hay churn por cliente final de la bodega. Crear lib/churn/customer-churn.ts con score 0-100 basado en días desde última compra vs promedio, reducción ticket medio, drop frecuencia. Tab 'En riesgo' en CRM + 1 click WhatsApp cupón recuperación.",
    tier: "A",
    scope: "admin",
    type: "new",
    impact: "Reactivación targetable de clientes dormidos. Recovery ~25% con WhatsApp+cupón.",
    effort: "M",
    priority: "P1",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "oc-sugerida-auto-reorder-hitl",
    number: 20,
    title: "OC sugerida auto-creada desde auto-reorder",
    description:
      "lib/forecasting/auto-reorder.ts calcula reposición sugerida pero nadie crea la OC automáticamente. Cron diario revisa stock vs ROP → crea OC draft agrupada por proveedor preferido. Notificación WhatsApp al dueño: 'Tienes 3 OC sugeridas para revisar'. HITL approval.",
    tier: "A",
    scope: "admin",
    type: "complete",
    impact: "Ahorra 1-2 horas/semana al dueño. Elimina la 'hoja Excel mental' diaria.",
    effort: "M",
    priority: "P1",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "conciliacion-bancaria-csv",
    number: 21,
    title: "Conciliación bancaria real (CSV BCP/Interbank/BBVA)",
    description:
      "TesoreriaModule tiene BankReconciliationTab pero es UI sin backend real. Implementar upload CSV/OFX → match automático contra movimientos internos con tolerancia S/0.50 → marcar conciliado. Parsers por banco (BCP, Interbank, BBVA, Scotiabank).",
    tier: "A",
    scope: "admin",
    type: "new",
    impact: "Elimina 2-3 horas/semana de conciliación manual. Foundation para contabilidad completa.",
    effort: "L",
    priority: "P1",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "pedido-recurrente-suscripcion",
    number: 22,
    title: "Pedido recurrente / suscripción",
    description:
      "'No quiero pensar en comprar arroz cada mes' → lo que hace que Costco, Amazon Subscribe & Save y Rappi Turbo sean máquinas de cash. Nuevo modelo Subscription { customerPhone, items, cadence, nextRunAt, active, tenantId }. Cron diario crea órdenes pendientes con aviso WhatsApp 24h antes. Toggle 'Suscribirse' en ProductDetailClient.",
    tier: "A",
    scope: "store",
    type: "new",
    impact: "LTV +2-3x, MRR predecible, churn reducido. Santo grial del retail recurrente.",
    effort: "L",
    priority: "P1",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "boleta-ruc-checkout",
    number: 23,
    title: "Boleta/RUC en checkout",
    description:
      "Desbloquea B2B. El mercado informal de Pucallpa tiene muchos micro-empresarios (puesto en mercado, kiosco, cevichería) que compran al por mayor. StepDatos: agregar 'Boleta o Factura'. Si Factura → RUC + razón social + lookup SUNAT. Customer model ya tiene tipoPersona/razonSocial definidos pero checkout no los pide.",
    tier: "A",
    scope: "store",
    type: "new",
    impact: "AOV B2B +80%, desbloquea clientes mayoristas. Típicamente 3-5x mayor ticket.",
    effort: "M",
    priority: "P1",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "auto-reorder-comprar-siempre",
    number: 24,
    title: "Auto-reorder 'comprar lo de siempre'",
    description:
      "La señora de 55 años compra lo mismo casi siempre (arroz, aceite, azúcar, gas, leche). Pedirle navegar el catálogo cada vez es fricción. Elevar LastOrderBanner a banner fijo en Hero. QuickReorderModal desde MobileBottomNav nuevo ítem 'Repetir'. CTA principal en /cuenta: '🔄 Repetir último pedido'.",
    tier: "A",
    scope: "store",
    type: "expansion",
    impact: "Retention +40%, frecuencia +30%. Diferencia entre 'compro cuando me acuerdo' y 'Buleje es mi hábito'.",
    effort: "S",
    priority: "P1",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "feature-flags-per-tenant",
    number: 25,
    title: "Feature flags per-tenant (DB override)",
    description:
      "Hoy features se activan para TODOS o NADIE — riesgo catastrófico. Modelo TenantFeatureFlag + PlatformFeatureFlag (global). Helper isFeatureEnabled(flagKey, tenantId) con cache 60s. UI /superadmin/feature-flags con toggles + slider % rollout + targeting por plan/antigüedad/tenantId.",
    tier: "A",
    scope: "cross-cutting",
    type: "new",
    impact: "Desbloquea rollouts graduales 1%→100%, A/B de precios, canary releases. Plan B obligatorio single-founder.",
    effort: "M",
    priority: "P1",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "superadmin-2fa-totp-persistente",
    number: 26,
    title: "Superadmin 2FA real (TOTP persistente)",
    description:
      "lib/superadmin-2fa.ts usa Map en memoria → se pierde en cada redeploy Vercel. Migrar a TOTP real (RFC 6238) con secret persistente en DB + QR code en primer login + email/WhatsApp como fallback. PlatformUser { username, passwordHash, totpSecret, lastLoginIp }. Bypass env var para escape hatch.",
    tier: "A",
    scope: "superadmin",
    type: "expansion",
    impact: "Seguridad de la llave maestra. Compliance. Hoy 2FA es inservible por reinicio serverless.",
    effort: "S",
    priority: "P1",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "cost-tracking-per-tenant",
    number: 27,
    title: "Cost tracking per tenant",
    description:
      "Posible que un tenant 'free' esté costando S/50/mes en storage/AI mientras paga 0. Dashboard /superadmin/costs con: bytes Postgres, MB Vercel Blob, tokens Groq/OpenAI, requests API por tenant. Gross margin: (MRR[tenant] - cost[tenant]) / MRR[tenant]. TenantUsageSnapshot diario.",
    tier: "A",
    scope: "superadmin",
    type: "new",
    impact: "Identifica tenants parásito → upgrade forzado o sacar del free tier. -15% COGS.",
    effort: "M",
    priority: "P1",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["fix-platform-settings-mrr"],
    isCriticalBug: false,
  },
  {
    id: "conteo-ciclico-abc",
    number: 28,
    title: "Conteo cíclico ABC en inventario",
    description:
      "Auto-genera hoja de conteo semanal/mensual, prioriza SKUs A > B > C (clasificación ABC por valor de venta). Permite conteos parciales sin cerrar el almacén. Genera ajustes automáticos post-conteo con approval flow.",
    tier: "A",
    scope: "admin",
    type: "new",
    impact: "Mantiene exactitud de inventario >95% sin downtime. Anti-merma silenciosa.",
    effort: "M",
    priority: "P1",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "guest-checkout-real",
    number: 29,
    title: "Guest checkout real sin fricción",
    description:
      "Hoy el wizard empieza en step='cuenta' pidiendo buscar por teléfono antes de nada. La señora no quiere 'crear cuenta', quiere pagar. Cambiar default: abrir en 'datos', pedir teléfono al final (en confirmar). Detectar cliente existente por teléfono al final como opt-in para acumular puntos.",
    tier: "A",
    scope: "store",
    type: "expansion",
    impact: "Conversión checkout +15-25%. Cart abandonment es el problema #1 de e-commerce LATAM.",
    effort: "S",
    priority: "P1",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "scarcity-real-pdp-cards",
    number: 30,
    title: "Scarcity real en ProductCard + PDP",
    description:
      "Existe LastUnitsSection pero no está visible en ProductCard ni PDP individual. 'Solo quedan 3' usando stock live. Urgencia genuina (no fake scarcity) basada en producto.stock. Badge rojo + countdown si stock ≤ 5.",
    tier: "A",
    scope: "store",
    type: "expansion",
    impact: "Conversión +8-12% en productos con stock bajo.",
    effort: "S",
    priority: "P1",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "abandoned-cart-recovery-marketplace",
    number: 31,
    title: "Abandoned cart recovery real (quitar stub MarketplaceAbandonedCart)",
    description:
      "MarketplaceAbandonedCartsDB línea 805-875 tiene 4 métodos stub (save/markConverted/getAbandoned/markReminderSent) pero TODOS retornan null/void porque el modelo no existe en Prisma. TODO Sprint C Wave 4. Implementar migración + cron de recordatorios WhatsApp.",
    tier: "A",
    scope: "marketplace",
    type: "complete",
    impact: "En retail 70% carts abandonados. Reminder WhatsApp 2h recupera 15-25%.",
    effort: "M",
    priority: "P1",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },

  // ─── TIER B — 15 items (32-46) ───────────────────────────────────────────
  {
    id: "wishlist-persistente-cross-store",
    number: 32,
    title: "Wishlist persistente cross-store (extensión marketplace)",
    description:
      "Extensión del wishlist Tier A: cross-store (un único heart funciona en cualquier tienda del marketplace). Sync con localStorage si no hay phone. Notificaciones WhatsApp cuando baja precio.",
    tier: "B",
    scope: "marketplace",
    type: "expansion",
    impact: "Retention cross-store, remarketing por precio.",
    effort: "M",
    priority: "P2",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: ["wishlist-favoritos-cross-store"],
    isCriticalBug: false,
  },
  {
    id: "disputas-cliente-vendedor-sla",
    number: 33,
    title: "Disputas cliente-vendedor con SLA 48h",
    description:
      "Sin sistema de disputas, la plataforma carga con reputación de vendedores malos. Dispute { orderId, storeId, reason, description, photoUrls, status }. Cliente 'Reportar problema' en /marketplace/orden/[id]. 48h para responder vía chat D2. Admin escalation + refund automático.",
    tier: "B",
    scope: "marketplace",
    type: "new",
    impact: "Confianza comprador +25%, reduce chargebacks, protege marca Buleje.",
    effort: "M",
    priority: "P2",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "tiers-vendedor-subscription",
    number: 34,
    title: "Tiers de vendedor (free/pro/elite) con subscription",
    description:
      "Diversifica revenue. Hoy Buleje solo cobra comisión (inestable). Free 30 productos 5% comisión. Pro S/29 mes 200 productos 4% comisión + analytics. Elite S/99 mes ilimitado 3% comisión + top placement. StoreSubscription + gating por tier.",
    tier: "B",
    scope: "marketplace",
    type: "new",
    impact: "MRR predecible. 5x revenue diversification.",
    effort: "L",
    priority: "P2",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: ["billing-stripe-webhook-sync"],
    isCriticalBug: false,
  },
  {
    id: "cross-vendor-loyalty-unified",
    number: 35,
    title: "Cross-vendor loyalty points unificados",
    description:
      "Hoy loyalty solo incrementa Customer.loyaltyPoints sin LoyaltyTransaction (TODO). Un punto cross-vendor (1 point = 1 sol, uso en cualquier tienda) convierte Buleje en club estilo Belcorp/Tottus. Schema: LoyaltyTransaction { customerPhone, type, points, orderId, storeId }.",
    tier: "B",
    scope: "marketplace",
    type: "expansion",
    impact: "Retention +20%, LTV +15%, engagement cross-store.",
    effort: "M",
    priority: "P2",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "scorecard-proveedor-visible",
    number: 36,
    title: "Scorecard proveedor visible en PuntoDeCompraTab",
    description:
      "SupplierScorecard vive aislado en un tab propio. Elevarlo: al crear OC, mostrar grade A/B/C/D del proveedor + alerta roja si gradeD. Comparativa visual cuando hay múltiples proveedores del mismo producto.",
    tier: "B",
    scope: "admin",
    type: "complete",
    impact: "Decisiones de compra más informadas, reduce OC a proveedores problemáticos.",
    effort: "S",
    priority: "P2",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "use-table-export-hook",
    number: 37,
    title: "Hook universal useTableExport()",
    description:
      "20+ tabs implementan su propio export CSV/Excel/PDF con código duplicado. Crear useTableExport() hook + botón estándar en AdminModuleHeader. Reemplaza 20 implementaciones con 1 fuente de verdad.",
    tier: "B",
    scope: "admin",
    type: "complete",
    impact: "Menos código duplicado, consistencia UX, fix bugs en un solo lugar.",
    effort: "M",
    priority: "P2",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "command-palette-quick-actions",
    number: 38,
    title: "Quick actions en Command Palette (Ctrl+K)",
    description:
      "Hoy el Command Palette es solo navegación. Añadir acciones: 'Registrar gasto', 'Nueva venta', 'Cobrar fiado', 'Crear OC'. Ctrl+K → acción directa sin navegar.",
    tier: "B",
    scope: "admin",
    type: "expansion",
    impact: "Power users ganan velocidad 3-5x. Differentiator para usuarios frecuentes.",
    effort: "S",
    priority: "P2",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "unified-support-inbox",
    number: 39,
    title: "Unified Support Inbox cross-tenant",
    description:
      "SupportTicket ya existe en DB con subject/message/priority/status/reply pero NO hay UI de consumo. Página /superadmin/support estilo Gmail: lista + detalle, responder con templates, auto-close sin respuesta del tenant en 14d.",
    tier: "B",
    scope: "superadmin",
    type: "new",
    impact: "Inbox único para single-founder. Datos ya en DB, solo falta UI.",
    effort: "S",
    priority: "P2",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "tenant-lifecycle-timeline",
    number: 40,
    title: "Tenant Lifecycle Timeline (Kanban)",
    description:
      "Vista /superadmin/lifecycle con 5 columnas Kanban: Trial → Onboarded → Active → At-Risk → Churned. Cada tarjeta tenant draggable con MRR, último pedido, signal activo. Click → TenantDetailModal con botones: WhatsApp / Email / Extender trial / Impersonate.",
    tier: "B",
    scope: "superadmin",
    type: "new",
    impact: "Single-operator necesita 'una pantalla que le diga a quién llamar hoy'. Estilo HubSpot.",
    effort: "M",
    priority: "P2",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["churn-engine-cron-playbook"],
    isCriticalBug: false,
  },
  {
    id: "pos-offline-indexeddb",
    number: 41,
    title: "POS offline-first persistente IndexedDB",
    description:
      "usePOSOffline existe pero no usa IndexedDB persistente para carritos + sincronización al volver online. Importante para bodegas con internet intermitente (Pucallpa).",
    tier: "B",
    scope: "admin",
    type: "complete",
    impact: "POS funciona sin internet. Elimina pérdida de ventas por cortes.",
    effort: "M",
    priority: "P2",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "cache-pattern-replication",
    number: 42,
    title: "Cache pattern replication (home promos, product list, settings)",
    description:
      "Hoy solo getCachedReviewStats usa 'use cache' + cacheTag + cacheLife. Replicar patrón para home promos (cacheLife minutes), product list por categoría (cacheLife hours), store settings (cacheLife days). Copy-paste con tags distintos.",
    tier: "B",
    scope: "cross-cutting",
    type: "expansion",
    impact: "-400ms LCP, -60% invocaciones Vercel en 3 rutas más visitadas.",
    effort: "S",
    priority: "P2",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "csp-tightening",
    number: 43,
    title: "CSP tightening (quitar unsafe-eval)",
    description:
      "lib/middleware-utils.ts script-src tiene 'unsafe-eval' (requerido por edge runtime). Mover páginas públicas (home, tienda, categoría) a node runtime → eliminar unsafe-eval. style-src unsafe-inline por Tailwind JIT reemplazar por nonce.",
    tier: "B",
    scope: "cross-cutting",
    type: "expansion",
    impact: "Mitiga XSS, compliance CSP strict.",
    effort: "S",
    priority: "P2",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "csrf-double-submit-cookie",
    number: 44,
    title: "CSRF double-submit cookie",
    description:
      "Cookies admin son sameSite strict pero active-tenant es lax. Endpoints de mutación tenant no validan CSRF token. Middleware inyecta CSRF token en cookie + header X-CSRF-Token obligatorio en writes.",
    tier: "B",
    scope: "cross-cutting",
    type: "new",
    impact: "Cierra vector CSRF real. Protección admin mutations.",
    effort: "S",
    priority: "P2",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "2fa-tenant-admin-totp",
    number: 45,
    title: "2FA para tenant admin (TOTP)",
    description:
      "Extender lib/superadmin-2fa.ts pattern a tenant admins. Nueva tabla AdminUser2FA { userId, secret, enabled }. Flujo enrollment en /admin/settings/security + check en requireAdmin cuando twoFactorEnabled.",
    tier: "B",
    scope: "cross-cutting",
    type: "new",
    impact: "Protección cuentas admin tenant. Mitiga credential stuffing.",
    effort: "S",
    priority: "P2",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: ["superadmin-2fa-totp-persistente"],
    isCriticalBug: false,
  },
  {
    id: "admin-mobile-bottom-bar",
    number: 46,
    title: "Admin mobile bottom bar con 5 accesos",
    description:
      "AdminMobileBottomBar existe pero poco usado. Elevarlo: 5 accesos directos fijos (POS / Fiados / Pedidos / Inventario / Más) siempre visibles en mobile. Atajo para operación móvil.",
    tier: "B",
    scope: "admin",
    type: "complete",
    impact: "UX mobile mucho más rápida para dueños que operan desde celular.",
    effort: "S",
    priority: "P2",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },

  // ─── TIER C — 38 items (47-84) ───────────────────────────────────────────
  {
    id: "flash-sales-cross-vendor",
    number: 47,
    title: "Flash sales cross-vendor (Black Friday Pucallpa)",
    description:
      "Eventos tipo 'Todos los pollos a S/12 este viernes 6-9pm'. Página /marketplace/flash con countdown. Schema FlashSale + FlashSaleProduct. Integración con sponsored-ranker: flash items boost automático.",
    tier: "C",
    scope: "marketplace",
    type: "new",
    impact: "Picos de tráfico +300% en eventos. Buzz local.",
    effort: "M",
    priority: "P3",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "banners-platform-wide-rotativos",
    number: 48,
    title: "Banners platform-wide rotativos (ads-as-a-service)",
    description:
      "Extender StoreBanner con section='platform_hero' + rotación ponderada por bid, igual que SponsoredBoost. Componente PlatformBannerCarousel en MarketplaceContent.",
    tier: "C",
    scope: "marketplace",
    type: "expansion",
    impact: "Nueva fuente de revenue CPM/CPC. S/20/día por bodeguero chico.",
    effort: "S",
    priority: "P3",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "catalog-lazy-virtualization",
    number: 49,
    title: "Lazy loading virtualizado del catálogo",
    description:
      "CatalogView.tsx con 200+ productos renderiza 200 DOM nodes — freezing en mobile bajo (Moto E6 en Pucallpa). Instalar @tanstack/react-virtual, reemplazar .map() por useVirtualizer con columnas dinámicas.",
    tier: "C",
    scope: "marketplace",
    type: "fix",
    impact: "TTI -40% mobile, scroll fluido 500+ productos, LCP mejora.",
    effort: "S",
    priority: "P3",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "recently-viewed-persistent",
    number: 50,
    title: "Recently viewed + historial búsquedas persistente",
    description:
      "Hook useRecentlyViewed que guarda últimos 20 en localStorage. Banda 'Visto recientemente' en MarketplaceContent arriba de PersonalizedRecommendations. Cross-device si hay customerPhone.",
    tier: "C",
    scope: "marketplace",
    type: "new",
    impact: "+10% re-engagement. 30% de compras vienen de 'visto recientemente'.",
    effort: "S",
    priority: "P3",
    researchFile: "marketplace-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "libro-mayor-contable",
    number: 51,
    title: "Libro mayor automático (doble partida)",
    description:
      "Asientos dobles por cada venta/compra/gasto/fiado/préstamo. Foundation para balance general contable real. Tabla JournalEntry con DEBE/HABER. Cierre mensual automático.",
    tier: "C",
    scope: "admin",
    type: "new",
    impact: "Contabilidad real sin Excel paralelo. Compliance SUNAT.",
    effort: "XL",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "empty-states-accionables",
    number: 52,
    title: "Empty states accionables con CTA + video",
    description:
      "Hoy solo CRM lo hace. Inventario/Compras/Fiados/Recetas muestran tabla vacía. Cada módulo debe tener: ícono grande, frase explicando valor, video 30s Loom, CTA accionable.",
    tier: "C",
    scope: "admin",
    type: "expansion",
    impact: "Feature adoption +30%, menos 'abro panel, veo 17 íconos, cierro'.",
    effort: "M",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "analytics-reubicacion-modulos",
    number: 53,
    title: "Mover ABCAnalysis + ExpiryDashboard a Inventario",
    description:
      "ABCAnalysisTab + ExpiryDashboard hoy viven sueltos en Analytics-Pro pero son features 100% de inventario. Reubicación dentro del módulo Inventario donde el usuario los busca.",
    tier: "C",
    scope: "admin",
    type: "complete",
    impact: "UX coherente. Features visibles donde se necesitan.",
    effort: "S",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "loyalty-transaction-persist",
    number: 54,
    title: "Persistir LoyaltyTransaction (TD-030 abierto)",
    description:
      "Hoy solo se guarda balance en Customer.loyaltyPoints, no historial. TD-030 abierto. El cliente no puede ver de dónde vinieron sus puntos. Modelo LoyaltyTransaction { customerPhone, type, points, orderId, description }.",
    tier: "C",
    scope: "admin",
    type: "complete",
    impact: "Historial auditable de puntos. Desbloquea canje controlado.",
    effort: "S",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "scoring-credit-7-todos",
    number: 55,
    title: "Scoring crediticio — resolver 7 TODOs",
    description:
      "ScoringCrediticioTab tiene 7 TODOs pendientes: re-score automático post-venta, historial de cambios, explicabilidad del score, umbral configurable, etc. Motor de 5 factores existe (lib/credit/scoring-engine.ts).",
    tier: "C",
    scope: "admin",
    type: "complete",
    impact: "Módulo scoring listo para producción. Decisiones de fiado automatizadas.",
    effort: "S",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "superadmin-ip-allowlist",
    number: 56,
    title: "Superadmin IP allowlist + lockout tras N fallos",
    description:
      "Config en PlatformSettings con lista de IPs permitidas. Login check: IP no matchea → 403. Lockout: 5 fallos en 15min → bloqueo 1h + alerta WhatsApp a Brandon. Escape: one-time recovery email.",
    tier: "C",
    scope: "superadmin",
    type: "expansion",
    impact: "Defensa llave maestra. Cierre de brute force.",
    effort: "S",
    priority: "P3",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["fix-platform-settings-mrr"],
    isCriticalBug: false,
  },
  {
    id: "weekly-digest-founder",
    number: 57,
    title: "Weekly digest email al founder",
    description:
      "Cron semanal lunes 8am que envía a Brandon: MRR Δ, signups, churn, top 3 at-risk, payments failed, red flags. Template HTML simple con tabla + links directos al panel.",
    tier: "C",
    scope: "superadmin",
    type: "new",
    impact: "Disciplina operativa sin abrir dashboard. Push medium que fuerza decisión.",
    effort: "S",
    priority: "P3",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["billing-stripe-webhook-sync", "churn-engine-cron-playbook"],
    isCriticalBug: false,
  },
  {
    id: "tenant-snapshot-backup",
    number: 58,
    title: "Tenant snapshot / backup on-demand",
    description:
      "Botón 'crear snapshot' en cada tenant → exporta JSON completo (Products + Orders + Customers + Settings) a Vercel Blob con retención 30d. Restore API protegida. V1 export-only, V2 restore.",
    tier: "C",
    scope: "superadmin",
    type: "new",
    impact: "CYA legal + rescate de data perdida + compliance Ley 29733.",
    effort: "L",
    priority: "P3",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "audit-trail-superadmin-dedicated",
    number: 59,
    title: "Audit trail dedicado de SuperAdmin",
    description:
      "Vista /superadmin/audit filtrada solo a acciones superadmin (excluye tenants). Cada impersonation (quién, cuándo, tenant, duración), cambio de plan, delete/purge, nuclear reset. Export CSV. Permanent retention.",
    tier: "C",
    scope: "superadmin",
    type: "expansion",
    impact: "Compliance Ley 29733, defensa legal, cadena de custodia.",
    effort: "S",
    priority: "P3",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "delivery-schedule-slots",
    number: 60,
    title: "Delivery schedule (slots horarios)",
    description:
      "En lugar de 'cuando puedas', dar slots horarios al cliente (9-11am, 11-1pm, etc.). Reduce quejas '¿a qué hora llega?'. Integra con DeliveryRoute existente.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "Reduce quejas, +CSAT, expectativas claras.",
    effort: "M",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "reviews-fotos-filters",
    number: 61,
    title: "Reviews con fotos + filtros + verified-buyer badge",
    description:
      "Reviews con upload de fotos (ya existe), filtros por rating, badge 'verified buyer' si review pertenece a Order real del cliente. Sort por útiles.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "Trust, conversión +5-8%.",
    effort: "M",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "busqueda-voz-consolidada",
    number: 62,
    title: "Búsqueda por voz en español PE consolidada",
    description:
      "Ya hay voice search en Header. Consolidar + historial + 'búsquedas frecuentes'. UX señora 55 años que no quiere teclear. Web Speech API con español-PE.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "UX señora 55 años. Diferenciador accessibility.",
    effort: "S",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "whatsapp-post-compra",
    number: 63,
    title: "WhatsApp como canal de post-compra",
    description:
      "Tracking + confirmación automática vía WhatsApp. 'Tu pedido salió para entrega. Llegará en 20min'. Botón 'Marcar recibido' en mensaje. Reduce llamadas soporte.",
    tier: "C",
    scope: "store",
    type: "new",
    impact: "Confianza, reduce llamadas soporte, canal principal en Pucallpa.",
    effort: "M",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "saved-lists-compartibles",
    number: 64,
    title: "Listas de compras compartibles ('mi lista mensual')",
    description:
      "Existe SavedShoppingList pero poco expuesta. Elevarla: 'mi lista mensual abarrotes' compartible via WhatsApp link. Una sola tap → agregar toda la lista al carrito.",
    tier: "C",
    scope: "store",
    type: "new",
    impact: "Retention, frecuencia, viralidad vía compartir.",
    effort: "S",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "capacitor-fcm-nativo",
    number: 65,
    title: "Capacitor FCM push nativo",
    description:
      "Hoy solo web-push. En APK Android no funcionan. Agregar @capacitor/cli + @capacitor/push-notifications + FCM. Registrar endpoint como variante en PushSubscriptionsStore.",
    tier: "C",
    scope: "cross-cutting",
    type: "expansion",
    impact: "Push reales en app nativa. Re-engagement móvil.",
    effort: "M",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "quechua-i18n-checkout",
    number: 66,
    title: "Quechua i18n en checkout",
    description:
      "lib/i18n.ts tiene 30 keys es/qu hardcoded pero no se consume en UI. Conectar a cookies().get('locale') + hook useT(). Llenar keys de checkout. Diferenciador 'única tienda online que habla quechua en Ucayali'.",
    tier: "C",
    scope: "cross-cutting",
    type: "expansion",
    impact: "Mercado rural Ucayali. Diferenciador marketing único.",
    effort: "M",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "health-check-deep-consolidated",
    number: 67,
    title: "Health check consolidado /api/health/deep",
    description:
      "Un solo endpoint que testea DB ping + Redis ping + BullMQ queue count + VAPID keys + stripe webhook registration. Alerta única en Sentry cuando un componente cae.",
    tier: "C",
    scope: "cross-cutting",
    type: "expansion",
    impact: "MTTR reducido. Observabilidad centralizada.",
    effort: "S",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "ai-cost-control-circuit-breaker",
    number: 68,
    title: "AI cost control + circuit breaker",
    description:
      "lib/ai-usage-tracker.ts y circuit-breaker.ts existen. Pegarlos al llm-router.ts L81 (callLLM): antes de la llamada, tracker.check(tier) — si excede budget, romper circuito y degradar a fallback rule-based. Protege contra runaway costs por prompt injection.",
    tier: "C",
    scope: "cross-cutting",
    type: "expansion",
    impact: "Previene runaway costs. Protección contra prompt injection en bucle.",
    effort: "S",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "db-indexes-wave-1",
    number: 69,
    title: "DB indexes wave 1 (TD-018)",
    description:
      "Plan migration-plan-indices-ola1-2026-04-09.md ya existe. Aplicar: índice compuesto (tenantId, createdAt DESC) a Sale, Order, ActivityLog → queries dashboard admin de ~400ms a ~40ms. Habilitar pg_stat_statements.",
    tier: "C",
    scope: "cross-cutting",
    type: "complete",
    impact: "-90% latencia en queries hot del dashboard admin.",
    effort: "S",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "progress-bar-loyalty-tier",
    number: 70,
    title: "Progress bar del loyalty tier visible",
    description:
      "El auto-discount engine existe (Nuevo 0%, Conocido 2%, Habitual 4%, VIP 6%) pero nadie se lo dice al cliente. Componente LoyaltyProgress en CheckoutModal + emails: 'Te faltan 3 compras para ser Habitual y ahorrar 4%'.",
    tier: "C",
    scope: "product-ux",
    type: "new",
    impact: "Repeat purchase +10-15%. Zeigarnik effect.",
    effort: "S",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "modo-senora-mayor",
    number: 71,
    title: "Modo 'señora mayor' — sidebar simplificado",
    description:
      "Sidebar simplificado con solo 5 módulos core (POS / Productos / Plata / Clientes / Fiados) + toggle a modo avanzado. Reduce overwhelm.",
    tier: "C",
    scope: "product-ux",
    type: "expansion",
    impact: "Menor churn D30 usuarios no-tech. UX accessible.",
    effort: "S",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "comunidad-whatsapp-bodegueros",
    number: 72,
    title: "Comunidad WhatsApp de bodegueros Buleje",
    description:
      "Grupo WhatsApp con playbooks, precios mayoristas, tips. Dueño = Brandon. Belonging + social proof + growth loop.",
    tier: "C",
    scope: "product-ux",
    type: "new",
    impact: "NPS +20pts, churn -25% por belonging/social proof.",
    effort: "S",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "pos-interactivo-onboarding",
    number: 73,
    title: "POS interactivo en onboarding (aha moment real)",
    description:
      "Step 4 del wizard son 3 cards estáticas. Reemplazar por mini-POS con 3 productos hardcoded (Arroz/Inka Cola/Pan), 'vender' arroz, simular Yape, confetti + 'hiciste tu primera venta'. Aha moment real.",
    tier: "C",
    scope: "product-ux",
    type: "expansion",
    impact: "Retention D7 +20%. Onboardings interactivos 2-3x mejor retention.",
    effort: "M",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "pricing-soles-yape",
    number: 74,
    title: "Plan Pro en soles + Yape/Plin",
    description:
      "Planes hoy en USD ($49). Cambiar a soles (S/185). Toggle mensual/anual. Integrar Yape/Plin Business para pagos recurrentes (además de Stripe).",
    tier: "C",
    scope: "product-ux",
    type: "expansion",
    impact: "Conversion free→pro +40-60% (psicológico en Perú).",
    effort: "S",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "notif-push-almuerzo",
    number: 75,
    title: "Notif push 'llevas S/X hoy' al mediodía",
    description:
      "PWA badge + push web a las 12pm: 'Ayer vendiste S/X, hoy llevas S/Y'. Momento natural para abrir el panel (almuerzo).",
    tier: "C",
    scope: "product-ux",
    type: "new",
    impact: "Sesiones/día +30%. Hábito natural.",
    effort: "S",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "referral-program-duenos",
    number: 76,
    title: "Referral program para dueños de bodega",
    description:
      "Hoy referral solo existe para clientes finales. Extender: 'Trae 1 bodega amiga → 1 mes gratis ambas'. Growth loop orgánico.",
    tier: "C",
    scope: "product-ux",
    type: "new",
    impact: "CAC ↓40% via growth loop. Viralidad orgánica.",
    effort: "M",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "checkout-sin-email-magic",
    number: 77,
    title: "Checkout sin email (magic-link WhatsApp)",
    description:
      "Checkout pide email pero 70% de señoras en Pucallpa no usa email activamente. Cambiar: solo teléfono + nombre. Magic-link por WhatsApp para retorno.",
    tier: "C",
    scope: "product-ux",
    type: "expansion",
    impact: "Conversion checkout +12-18% señora 55 años.",
    effort: "M",
    priority: "P3",
    researchFile: "product-ux-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "pwa-install-prompt-aggressive",
    number: 78,
    title: "PWA install prompt agresivo post-compra",
    description:
      "Prompt agresivo post-primera-compra 'Instala Buleje en tu pantalla' + push notifications de estado. Retention +25-40%.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "Retention +25-40%, re-engagement via push.",
    effort: "S",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "direccion-mapa-foto-referencia",
    number: 79,
    title: "Dirección con mapa + foto de referencia",
    description:
      "En lugar de texto libre de dirección, mapa interactivo + foto del portón/fachada como referencia visual. Reduce delivery fallidos por 'no sé dónde es'.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "Reduce delivery fallidos -60%.",
    effort: "M",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "combo-con-lo-que-compras",
    number: 80,
    title: "'Combo con lo que compras' dinámico",
    description:
      "Upsell inteligente en carrito basado en co-purchased API ya existente. 'Clientes que compraron Arroz + Aceite también llevaron Azúcar'. Add button rápido.",
    tier: "C",
    scope: "store",
    type: "expansion",
    impact: "AOV +10-15%.",
    effort: "S",
    priority: "P3",
    researchFile: "store-individual-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "devoluciones-proveedor-workflow",
    number: 81,
    title: "Devoluciones proveedor con workflow de aprobación",
    description:
      "DevolucionesProveedorModule funcional pero sin workflow de aprobación ni motivo tipificado. Agregar enum de motivos + aprobación multinivel + generación de nota de crédito automática.",
    tier: "C",
    scope: "admin",
    type: "complete",
    impact: "Control de devoluciones, evidencia trazable.",
    effort: "S",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "weather-aware-demand-predictor",
    number: 82,
    title: "Weather-aware demand predictor",
    description:
      "DemandPrediction existe con media móvil ponderada. WeatherDemandPredictor es mock. Integrar weather API real (OpenWeatherMap Pucallpa) → 'llueve mañana, sube stock de gaseosas'.",
    tier: "C",
    scope: "admin",
    type: "complete",
    impact: "Predicción 20-30% más precisa en productos weather-sensitive.",
    effort: "M",
    priority: "P3",
    researchFile: "admin-modules-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "ocr-facturas-proveedor",
    number: 83,
    title: "OCR de facturas de proveedor",
    description:
      "Subir foto de factura en papel → parse con Groq vision → crear PurchaseOrder automática. Elimina digitación manual de facturas recibidas.",
    tier: "C",
    scope: "cross-cutting",
    type: "new",
    impact: "Elimina ~30 min/día de digitación manual de facturas.",
    effort: "M",
    priority: "P3",
    researchFile: "cross-cutting-improvements-2026-04-09.md",
    dependencies: [],
    isCriticalBug: false,
  },
  {
    id: "gdpr-29733-export-tenant",
    number: 84,
    title: "GDPR / Ley 29733 export tenant",
    description:
      "Endpoint 'exportar todos los datos del tenant' (JSON/CSV) para data subject requests. Compliance Ley 29733 Perú + GDPR. Reusar lógica del snapshot backup.",
    tier: "C",
    scope: "superadmin",
    type: "new",
    impact: "Compliance legal Perú + GDPR. Evita multas.",
    effort: "S",
    priority: "P3",
    researchFile: "superadmin-improvements-2026-04-09.md",
    dependencies: ["tenant-snapshot-backup"],
    isCriticalBug: false,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Helper getters
// ────────────────────────────────────────────────────────────────────────────

export const ROADMAP_ITEMS_BY_ID: Readonly<Record<string, RoadmapItem>> = Object.freeze(
  Object.fromEntries(ROADMAP_ITEMS.map((item) => [item.id, item])),
);

export const ROADMAP_TOTAL = ROADMAP_ITEMS.length;

export function getRoadmapItem(id: string): RoadmapItem | undefined {
  return ROADMAP_ITEMS_BY_ID[id];
}

export function getCriticalBugs(): RoadmapItem[] {
  return ROADMAP_ITEMS.filter((item) => item.isCriticalBug);
}

export function getRoadmapByTier(tier: RoadmapTier): RoadmapItem[] {
  return ROADMAP_ITEMS.filter((item) => item.tier === tier);
}
