/**
 * Mock data para Deals MVP — 30 productos con descuentos reales.
 * ADR: temporal, reemplazar con API real cuando exista endpoint deals-side.
 * No conecta a orders.db.ts ni a Prisma.
 */

export type DealCategory =
  | "abarrotes"
  | "frescos"
  | "bebidas"
  | "limpieza"
  | "lacteos"
  | "farmacia";

export type Deal = {
  id: string;
  name: string;
  category: DealCategory;
  price: number;
  previousPrice: number;
  discountPct: number;
  unit: string;
  storeName: string;
  storeSlug: string;
  /** Logo de la tienda — avatar en el card. */
  storeLogo?: string | null;
  /** ISO timestamp cuando termina la oferta */
  endsAt: string;
  isFlash: boolean;
  /** Campos opcionales para integrar con UnifiedProductCard (carrito + modal). */
  productId?: number;
  storeProductId?: string;
  image?: string | null;
  stock?: number;
};

export type DealStore = {
  id: string;
  name: string;
  slug: string;
  zone: string;
  activeDeals: number;
  maxDiscountPct: number;
  avgDiscountPct: number;
};

// Termina en 2d 14h desde ahora (relativo al build, solo para UI)
const in2days = () => new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString();
const in24h = () => new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
const in6h = () => new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString();

export const MOCK_DEALS: Deal[] = [
  // FLASH (24h)
  {
    id: "deal_001",
    name: "Arroz Costeño Extra 5 kg",
    category: "abarrotes",
    price: 18.9,
    previousPrice: 24.5,
    discountPct: 23,
    unit: "saco",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in24h(),
    isFlash: true,
  },
  {
    id: "deal_002",
    name: "Aceite Primor Vegetal 1L",
    category: "abarrotes",
    price: 6.5,
    previousPrice: 9.9,
    discountPct: 34,
    unit: "botella",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in24h(),
    isFlash: true,
  },
  {
    id: "deal_003",
    name: "Pollo Entero Nacional",
    category: "frescos",
    price: 11.9,
    previousPrice: 16.5,
    discountPct: 28,
    unit: "kg",
    storeName: "Carniceria Centro",
    storeSlug: "carniceria-centro",
    endsAt: in6h(),
    isFlash: true,
  },
  {
    id: "deal_004",
    name: "Inca Kola 3L",
    category: "bebidas",
    price: 7.2,
    previousPrice: 9.5,
    discountPct: 24,
    unit: "botella",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in24h(),
    isFlash: true,
  },
  {
    id: "deal_005",
    name: "Detergente Ace 4.5 kg",
    category: "limpieza",
    price: 22.5,
    previousPrice: 32.0,
    discountPct: 30,
    unit: "bolsa",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in24h(),
    isFlash: true,
  },
  {
    id: "deal_006",
    name: "Leche Gloria Entera 400g",
    category: "lacteos",
    price: 3.5,
    previousPrice: 5.1,
    discountPct: 31,
    unit: "tarro",
    storeName: "Minimarket Yarinacocha",
    storeSlug: "minimarket-yarinacocha",
    endsAt: in6h(),
    isFlash: true,
  },
  // SEMANA
  {
    id: "deal_007",
    name: "Fideos Don Vittorio Spaghetti 500g",
    category: "abarrotes",
    price: 2.5,
    previousPrice: 3.1,
    discountPct: 19,
    unit: "paquete",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_008",
    name: "Azucar Rubia 1 kg",
    category: "abarrotes",
    price: 2.8,
    previousPrice: 3.5,
    discountPct: 20,
    unit: "kg",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_009",
    name: "Atun Florida en Aceite 170g",
    category: "abarrotes",
    price: 2.1,
    previousPrice: 3.0,
    discountPct: 30,
    unit: "lata",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_010",
    name: "Sal Marina Emsal 500g",
    category: "abarrotes",
    price: 0.9,
    previousPrice: 1.5,
    discountPct: 40,
    unit: "bolsa",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_011",
    name: "Tomate rojo kilo",
    category: "frescos",
    price: 2.0,
    previousPrice: 3.5,
    discountPct: 43,
    unit: "kg",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_012",
    name: "Limones verdes kilo",
    category: "frescos",
    price: 1.5,
    previousPrice: 2.5,
    discountPct: 40,
    unit: "kg",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_013",
    name: "Cebolla roja kilo",
    category: "frescos",
    price: 1.8,
    previousPrice: 2.8,
    discountPct: 36,
    unit: "kg",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_014",
    name: "Coca Cola 3L",
    category: "bebidas",
    price: 6.8,
    previousPrice: 8.5,
    discountPct: 20,
    unit: "botella",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_015",
    name: "Agua San Luis 2.5L",
    category: "bebidas",
    price: 1.5,
    previousPrice: 2.5,
    discountPct: 40,
    unit: "botella",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_016",
    name: "Chicha Morada 1L",
    category: "bebidas",
    price: 3.2,
    previousPrice: 4.5,
    discountPct: 29,
    unit: "botella",
    storeName: "Panaderia Yarinacocha",
    storeSlug: "panaderia-yarinacocha",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_017",
    name: "Jabon Bolivar x3",
    category: "limpieza",
    price: 4.5,
    previousPrice: 6.5,
    discountPct: 31,
    unit: "pack",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_018",
    name: "Lejia Clorox 900ml",
    category: "limpieza",
    price: 3.8,
    previousPrice: 5.5,
    discountPct: 31,
    unit: "botella",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_019",
    name: "Suavizante Downy 850ml",
    category: "limpieza",
    price: 8.9,
    previousPrice: 12.5,
    discountPct: 29,
    unit: "botella",
    storeName: "Minimarket Yarinacocha",
    storeSlug: "minimarket-yarinacocha",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_020",
    name: "Yogur Gloria Fresa 200ml",
    category: "lacteos",
    price: 2.2,
    previousPrice: 3.0,
    discountPct: 27,
    unit: "unid",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_021",
    name: "Queso Fresco 250g",
    category: "lacteos",
    price: 5.5,
    previousPrice: 7.5,
    discountPct: 27,
    unit: "bloque",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_022",
    name: "Mantequilla Gloria 200g",
    category: "lacteos",
    price: 6.2,
    previousPrice: 8.0,
    discountPct: 23,
    unit: "barra",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_023",
    name: "Paracetamol 500mg x20",
    category: "farmacia",
    price: 2.5,
    previousPrice: 4.0,
    discountPct: 38,
    unit: "caja",
    storeName: "Minimarket Yarinacocha",
    storeSlug: "minimarket-yarinacocha",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_024",
    name: "Alcohol en Gel 500ml",
    category: "farmacia",
    price: 4.5,
    previousPrice: 7.0,
    discountPct: 36,
    unit: "frasco",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_025",
    name: "Vitamina C 500mg x30",
    category: "farmacia",
    price: 5.9,
    previousPrice: 9.5,
    discountPct: 38,
    unit: "caja",
    storeName: "Minimarket Yarinacocha",
    storeSlug: "minimarket-yarinacocha",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_026",
    name: "Maizena 200g",
    category: "abarrotes",
    price: 1.8,
    previousPrice: 2.8,
    discountPct: 36,
    unit: "cajita",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_027",
    name: "Papas chips Lays Grande",
    category: "abarrotes",
    price: 4.5,
    previousPrice: 6.5,
    discountPct: 31,
    unit: "bolsa",
    storeName: "Buleje",
    storeSlug: "bodega-san-martin",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_028",
    name: "Espinaca fresca 1 atado",
    category: "frescos",
    price: 1.2,
    previousPrice: 2.0,
    discountPct: 40,
    unit: "atado",
    storeName: "Mercado Bellavista",
    storeSlug: "mercado-bellavista",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_029",
    name: "Cerveza Cristal 650ml",
    category: "bebidas",
    price: 4.5,
    previousPrice: 6.0,
    discountPct: 25,
    unit: "botella",
    storeName: "Licoreria Manantay",
    storeSlug: "licoreria-manantay",
    endsAt: in2days(),
    isFlash: false,
  },
  {
    id: "deal_030",
    name: "Papel Higienico Suave x12",
    category: "limpieza",
    price: 8.5,
    previousPrice: 12.0,
    discountPct: 29,
    unit: "pack",
    storeName: "Bodega Dona Elena",
    storeSlug: "bodega-dona-elena",
    endsAt: in2days(),
    isFlash: false,
  },
];

export const MOCK_DEAL_STORES: DealStore[] = [
  {
    id: "ds-1",
    name: "Bodega Dona Elena",
    slug: "bodega-dona-elena",
    zone: "Calleria",
    activeDeals: 9,
    maxDiscountPct: 34,
    avgDiscountPct: 27,
  },
  {
    id: "ds-2",
    name: "Buleje",
    slug: "bodega-san-martin",
    zone: "Manantay",
    activeDeals: 10,
    maxDiscountPct: 40,
    avgDiscountPct: 29,
  },
  {
    id: "ds-3",
    name: "Mercado Bellavista",
    slug: "mercado-bellavista",
    zone: "Calleria",
    activeDeals: 6,
    maxDiscountPct: 43,
    avgDiscountPct: 38,
  },
  {
    id: "ds-4",
    name: "Carniceria Centro",
    slug: "carniceria-centro",
    zone: "Yarinacocha",
    activeDeals: 1,
    maxDiscountPct: 28,
    avgDiscountPct: 28,
  },
  {
    id: "ds-5",
    name: "Minimarket Yarinacocha",
    slug: "minimarket-yarinacocha",
    zone: "Yarinacocha",
    activeDeals: 4,
    maxDiscountPct: 38,
    avgDiscountPct: 32,
  },
  {
    id: "ds-6",
    name: "Licoreria Manantay",
    slug: "licoreria-manantay",
    zone: "Manantay",
    activeDeals: 1,
    maxDiscountPct: 25,
    avgDiscountPct: 25,
  },
];

/** Totales para stats del hero (backend-derivados — solo display) */
export const DEALS_SUMMARY = {
  totalProducts: MOCK_DEALS.length,
  totalStores: MOCK_DEAL_STORES.length,
  /** ISO de cuando termina la oferta flash mas proxima */
  flashEndsAt: in24h(),
} as const;
