import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/require-admin";
import { RemindersDB } from "@/lib/db/reminders.db";
import { z } from "zod";
import { applyRateLimit } from "@/lib/rate-limit";
import { runWithAuditContext } from "@/lib/audit/audit-context";

const CreateSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(1000).default(""),
  type: z.enum(["pago", "inventario", "tarea", "vencimiento", "cliente", "general"]),
  priority: z.enum(["alta", "media", "baja"]).default("media"),
  dueDate: z.string().datetime(),
  autoGenerated: z.boolean().default(false),
});

const UpdateSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(1000).optional(),
  type: z.enum(["pago", "inventario", "tarea", "vencimiento", "cliente", "general"]).optional(),
  priority: z.enum(["alta", "media", "baja"]).optional(),
  status: z.enum(["pendiente", "completado", "vencido"]).optional(),
  dueDate: z.string().datetime().optional(),
});

function mapReminder(r: {
  id: string; tenantId: string; title: string; description: string;
  type: string; priority: string; status: string; dueDate: Date;
  autoGenerated: boolean; createdAt: Date; updatedAt: Date;
}) {
  return {
    id: r.id,
    title: r.title,
    description: r.description,
    type: r.type,
    priority: r.priority,
    status: r.status,
    dueDate: r.dueDate.toISOString().slice(0, 10),
    autoGenerated: r.autoGenerated,
    createdAt: r.createdAt.toISOString().slice(0, 10),
  };
}

// GET /api/reminders
export async function GET(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;

  // Auto-mark overdue on every GET
  await RemindersDB.markOverdue(auth.tenantId);

  const rows = await RemindersDB.list(auth.tenantId);
  return NextResponse.json(rows.map(mapReminder));
}

// POST /api/reminders
export async function POST(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;
  const rl = applyRateLimit(req, "MODERATE", "reminders");
  if (rl) return rl;

  return runWithAuditContext(req, auth.username, async () => {
    const body = await req.json();
    const parsed = CreateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
    }

    const row = await RemindersDB.create(auth.tenantId, parsed.data);
    return NextResponse.json(mapReminder(row), { status: 201 });
  });
}

// PATCH /api/reminders?id=xxx
export async function PATCH(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;

  return runWithAuditContext(req, auth.username, async () => {
    const id = req.nextUrl.searchParams.get("id");
    if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

    const body = await req.json();
    const parsed = UpdateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
    }

    const row = await RemindersDB.updateForTenant(auth.tenantId, id, parsed.data);
    if (!row) return NextResponse.json({ error: "not_found" }, { status: 404 });
    return NextResponse.json(mapReminder(row));
  });
}

// DELETE /api/reminders?id=xxx
export async function DELETE(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;
  const rl = applyRateLimit(req, "MODERATE", "reminders");
  if (rl) return rl;

  return runWithAuditContext(req, auth.username, async () => {
    const id = req.nextUrl.searchParams.get("id");
    if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

    const ok = await RemindersDB.deleteForTenant(auth.tenantId, id);
    if (!ok) return NextResponse.json({ error: "not_found" }, { status: 404 });
    return NextResponse.json({ ok: true });
  });
}
