export const dynamic = 'force-dynamic'
import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/require-admin";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { applyRateLimit } from "@/lib/rate-limit";

const CreateSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(1000).default(""),
  type: z.enum(["pago", "inventario", "tarea", "vencimiento", "cliente", "general"]),
  priority: z.enum(["alta", "media", "baja"]).default("media"),
  dueDate: z.string().datetime(),
  autoGenerated: z.boolean().default(false),
});

const UpdateSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(1000).optional(),
  type: z.enum(["pago", "inventario", "tarea", "vencimiento", "cliente", "general"]).optional(),
  priority: z.enum(["alta", "media", "baja"]).optional(),
  status: z.enum(["pendiente", "completado", "vencido"]).optional(),
  dueDate: z.string().datetime().optional(),
});

function mapReminder(r: {
  id: string; tenantId: string; title: string; description: string;
  type: string; priority: string; status: string; dueDate: Date;
  autoGenerated: boolean; createdAt: Date; updatedAt: Date;
}) {
  return {
    id: r.id,
    title: r.title,
    description: r.description,
    type: r.type,
    priority: r.priority,
    status: r.status,
    dueDate: r.dueDate.toISOString().slice(0, 10),
    autoGenerated: r.autoGenerated,
    createdAt: r.createdAt.toISOString().slice(0, 10),
  };
}

// GET /api/reminders
export async function GET(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;

  // Auto-mark overdue on every GET
  await prisma.reminder.updateMany({
    where: {
      tenantId: auth.tenantId,
      status: "pendiente",
      dueDate: { lt: new Date() },
    },
    data: { status: "vencido" },
  });

  const rows = await prisma.reminder.findMany({
    where: { tenantId: auth.tenantId },
    orderBy: [{ status: "asc" }, { dueDate: "asc" }],
  });

  return NextResponse.json(rows.map(mapReminder));
}

// POST /api/reminders
export async function POST(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;
  const rl = applyRateLimit(req, "MODERATE", "reminders");
  if (rl) return rl;

  const body = await req.json();
  const parsed = CreateSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const row = await prisma.reminder.create({
    data: {
      ...parsed.data,
      dueDate: new Date(parsed.data.dueDate),
      tenantId: auth.tenantId,
    },
  });

  return NextResponse.json(mapReminder(row), { status: 201 });
}

// PATCH /api/reminders?id=xxx
export async function PATCH(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;

  const id = req.nextUrl.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

  const body = await req.json();
  const parsed = UpdateSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const existing = await prisma.reminder.findFirst({ where: { id, tenantId: auth.tenantId } });
  if (!existing) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const { dueDate, ...rest } = parsed.data;
  const row = await prisma.reminder.update({
    where: { id },
    data: { ...rest, ...(dueDate && { dueDate: new Date(dueDate) }) },
  });

  return NextResponse.json(mapReminder(row));
}

// DELETE /api/reminders?id=xxx
export async function DELETE(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin", "cajero", "almacenero"]);
  if (auth instanceof NextResponse) return auth;
  const rl = applyRateLimit(req, "MODERATE", "reminders");
  if (rl) return rl;

  const id = req.nextUrl.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

  const existing = await prisma.reminder.findFirst({ where: { id, tenantId: auth.tenantId } });
  if (!existing) return NextResponse.json({ error: "not_found" }, { status: 404 });

  await prisma.reminder.delete({ where: { id } });

  return NextResponse.json({ ok: true });
}
