import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/require-admin";
import { prisma } from "@/lib/prisma";
import { logger } from "@/lib/logger";

/**
 * POST /api/admin/seed-peru-products
 * Seed 50 productos peruanos reales con imágenes, precios y stock.
 * Solo para tenant "main" — no afecta otras tiendas.
 */

const PRODUCTOS_PERU: Array<{
  name: string;
  price: number;
  costPrice: number;
  category: string;
  unit: string;
  stock: number;
  stockMin: number;
  stockMax: number;
  description: string;
  image: string;
  barcode: string;
  badge?: string;
}> = [
  // ═══════════════════════════════════════
  // ABARROTES (12 productos)
  // ═══════════════════════════════════════
  {
    name: "Arroz Costeño Extra 5kg",
    price: 24.90,
    costPrice: 19.50,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 120,
    stockMin: 20,
    stockMax: 150,
    description: "Arroz extra graneadito, grano largo. Producto peruano premium.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/27831418/20248536.jpg",
    barcode: "7751271001001",
    badge: "Popular",
  },
  {
    name: "Azúcar Rubia Cartavio 1kg",
    price: 4.80,
    costPrice: 3.60,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 90,
    stockMin: 15,
    stockMax: 120,
    description: "Azúcar rubia de caña peruana, endulzante natural.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/27188879/20201348.jpg",
    barcode: "7751271001002",
  },
  {
    name: "Aceite Primor Premium 1L",
    price: 11.90,
    costPrice: 8.90,
    category: "Abarrotes",
    unit: "botella",
    stock: 60,
    stockMin: 12,
    stockMax: 80,
    description: "Aceite vegetal premium, ideal para freír y cocinar.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/26aborres/20114689.jpg",
    barcode: "7751271001003",
    badge: "Oferta",
  },
  {
    name: "Fideos Don Vittorio Spaghetti 500g",
    price: 3.90,
    costPrice: 2.80,
    category: "Abarrotes",
    unit: "paquete",
    stock: 80,
    stockMin: 15,
    stockMax: 100,
    description: "Pasta spaghetti de sémola de trigo duro. Marca líder peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103099/20201710.jpg",
    barcode: "7751271001004",
  },
  {
    name: "Avena 3 Ositos con Quinua 600g",
    price: 5.50,
    costPrice: 3.90,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 45,
    stockMin: 8,
    stockMax: 60,
    description: "Avena enriquecida con quinua andina. Desayuno nutritivo peruano.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23587920/20201348.jpg",
    barcode: "7751271001005",
  },
  {
    name: "Lentejas Costeño 500g",
    price: 4.90,
    costPrice: 3.40,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 50,
    stockMin: 10,
    stockMax: 70,
    description: "Lentejas seleccionadas, ricas en hierro y proteínas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23038650/20211020.jpg",
    barcode: "7751271001006",
  },
  {
    name: "Sal Emsal Yodada 1kg",
    price: 1.80,
    costPrice: 1.10,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 70,
    stockMin: 15,
    stockMax: 100,
    description: "Sal de mesa yodada y fluorizada. Producida en Perú.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/15790032/20114703.jpg",
    barcode: "7751271001007",
  },
  {
    name: "Café Altomayo Instantáneo 200g",
    price: 18.90,
    costPrice: 14.00,
    category: "Abarrotes",
    unit: "frasco",
    stock: 25,
    stockMin: 5,
    stockMax: 40,
    description: "Café 100% peruano de la selva alta. Aroma intenso.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/26764440/20201430.jpg",
    barcode: "7751271001008",
    badge: "Peruano",
  },
  {
    name: "Huevos La Calera x30",
    price: 14.90,
    costPrice: 11.00,
    category: "Abarrotes",
    unit: "bandeja",
    stock: 20,
    stockMin: 5,
    stockMax: 30,
    description: "Huevos frescos de gallina, bandeja por 30 unidades.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/26108460/20201535.jpg",
    barcode: "7751271001009",
  },
  {
    name: "Atún Florida en Aceite 170g",
    price: 6.50,
    costPrice: 4.50,
    category: "Conservas",
    unit: "lata",
    stock: 55,
    stockMin: 10,
    stockMax: 80,
    description: "Filete de atún en aceite vegetal. Conserva proteica premium.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23107960/20201380.jpg",
    barcode: "7751271001010",
  },
  {
    name: "Sillao Kikko 500ml",
    price: 4.90,
    costPrice: 3.20,
    category: "Abarrotes",
    unit: "botella",
    stock: 30,
    stockMin: 5,
    stockMax: 45,
    description: "Salsa de soya oscura, esencial para chifa y cocina peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/19860520/20201398.jpg",
    barcode: "7751271001011",
  },
  {
    name: "Quinua Perlada Costeño 500g",
    price: 9.90,
    costPrice: 7.00,
    category: "Abarrotes",
    unit: "bolsa",
    stock: 35,
    stockMin: 8,
    stockMax: 50,
    description: "Quinua perlada andina, súper alimento peruano rico en proteínas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23587950/20211025.jpg",
    barcode: "7751271001012",
    badge: "Superfood",
  },

  // ═══════════════════════════════════════
  // BEBIDAS (10 productos)
  // ═══════════════════════════════════════
  {
    name: "Inca Kola 1.5L",
    price: 8.50,
    costPrice: 5.80,
    category: "Bebidas",
    unit: "botella",
    stock: 80,
    stockMin: 15,
    stockMax: 100,
    description: "La bebida del sabor nacional. Gaseosa dorada peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/25207660/20201450.jpg",
    barcode: "7751271002001",
    badge: "Popular",
  },
  {
    name: "Coca-Cola 1.5L",
    price: 8.50,
    costPrice: 5.80,
    category: "Bebidas",
    unit: "botella",
    stock: 70,
    stockMin: 15,
    stockMax: 100,
    description: "Refresco clásico, botella familiar.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23387710/20201448.jpg",
    barcode: "7751271002002",
  },
  {
    name: "Agua San Luis Sin Gas 2.5L",
    price: 3.50,
    costPrice: 2.10,
    category: "Bebidas",
    unit: "botella",
    stock: 60,
    stockMin: 12,
    stockMax: 80,
    description: "Agua de mesa, purificada y embotellada en Perú.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23587700/20201460.jpg",
    barcode: "7751271002003",
  },
  {
    name: "Chicha Morada Naturale 1L",
    price: 5.90,
    costPrice: 3.80,
    category: "Bebidas",
    unit: "botella",
    stock: 40,
    stockMin: 8,
    stockMax: 60,
    description: "Chicha morada lista para tomar. Bebida ancestral peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20490860/20201468.jpg",
    barcode: "7751271002004",
    badge: "Peruano",
  },
  {
    name: "Cerveza Cusqueña Dorada 620ml",
    price: 7.50,
    costPrice: 5.20,
    category: "Bebidas",
    unit: "botella",
    stock: 48,
    stockMin: 10,
    stockMax: 60,
    description: "Cerveza premium peruana, elaborada con malta importada.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20490880/20201478.jpg",
    barcode: "7751271002005",
  },
  {
    name: "Cerveza Pilsen Callao Pack x6",
    price: 25.90,
    costPrice: 19.00,
    category: "Bebidas",
    unit: "pack",
    stock: 20,
    stockMin: 5,
    stockMax: 35,
    description: "El sabor de la verdadera amistad. Pack six pack.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588100/20201480.jpg",
    barcode: "7751271002006",
  },
  {
    name: "Yogurt Gloria Fresa 1L",
    price: 7.90,
    costPrice: 5.80,
    category: "Lácteos",
    unit: "botella",
    stock: 30,
    stockMin: 8,
    stockMax: 45,
    description: "Yogurt bebible sabor fresa, fuente de calcio y probióticos.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588000/20201510.jpg",
    barcode: "7751271002007",
  },
  {
    name: "Emoliente San Luis 500ml",
    price: 2.50,
    costPrice: 1.50,
    category: "Bebidas",
    unit: "botella",
    stock: 35,
    stockMin: 8,
    stockMax: 50,
    description: "Bebida tradicional peruana a base de hierbas medicinales.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20490900/20211055.jpg",
    barcode: "7751271002008",
    badge: "Tradicional",
  },
  {
    name: "Jugo Frugos del Valle Durazno 1L",
    price: 4.90,
    costPrice: 3.30,
    category: "Bebidas",
    unit: "caja",
    stock: 40,
    stockMin: 8,
    stockMax: 60,
    description: "Néctar de durazno, enriquecido con vitaminas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103200/20201500.jpg",
    barcode: "7751271002009",
  },

  // ═══════════════════════════════════════
  // LÁCTEOS (5 productos)
  // ═══════════════════════════════════════
  {
    name: "Leche Gloria Entera 1L UHT",
    price: 7.20,
    costPrice: 5.60,
    category: "Lácteos",
    unit: "caja",
    stock: 50,
    stockMin: 10,
    stockMax: 70,
    description: "Leche entera UHT, la más consumida del Perú.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/24487680/20201520.jpg",
    barcode: "7751271003001",
    badge: "Popular",
  },
  {
    name: "Leche Evaporada Gloria 400ml",
    price: 4.90,
    costPrice: 3.80,
    category: "Lácteos",
    unit: "lata",
    stock: 80,
    stockMin: 15,
    stockMax: 100,
    description: "Leche evaporada entera, ideal para cocina y loncheras.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588200/20201522.jpg",
    barcode: "7751271003002",
  },
  {
    name: "Queso Fresco Laive 400g",
    price: 12.90,
    costPrice: 9.50,
    category: "Lácteos",
    unit: "unidad",
    stock: 15,
    stockMin: 3,
    stockMax: 25,
    description: "Queso fresco pasteurizado, ideal para desayunos y ensaladas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103300/20201530.jpg",
    barcode: "7751271003003",
  },
  {
    name: "Mantequilla Gloria con Sal 200g",
    price: 7.50,
    costPrice: 5.50,
    category: "Lácteos",
    unit: "barra",
    stock: 20,
    stockMin: 4,
    stockMax: 30,
    description: "Mantequilla con sal, cremosa y de sabor intenso.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103350/20201540.jpg",
    barcode: "7751271003004",
  },
  {
    name: "Manjar Blanco Bazo Velarde 500g",
    price: 9.90,
    costPrice: 7.00,
    category: "Lácteos",
    unit: "pote",
    stock: 18,
    stockMin: 4,
    stockMax: 30,
    description: "Manjar blanco artesanal, dulce tradicional peruano para postres.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103400/20211060.jpg",
    barcode: "7751271003005",
    badge: "Artesanal",
  },

  // ═══════════════════════════════════════
  // LIMPIEZA Y HOGAR (6 productos)
  // ═══════════════════════════════════════
  {
    name: "Detergente Bolívar Active Care 2.6kg",
    price: 18.90,
    costPrice: 13.50,
    category: "Limpieza",
    unit: "bolsa",
    stock: 25,
    stockMin: 5,
    stockMax: 40,
    description: "Detergente en polvo con poder quitamanchas. Marca peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/25207700/20201600.jpg",
    barcode: "7751271004001",
  },
  {
    name: "Lejía Clorox Tradicional 1L",
    price: 4.90,
    costPrice: 3.20,
    category: "Limpieza",
    unit: "botella",
    stock: 35,
    stockMin: 8,
    stockMax: 50,
    description: "Lejía desinfectante, elimina el 99.9% de gérmenes.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103500/20201610.jpg",
    barcode: "7751271004002",
  },
  {
    name: "Jabón Bolívar Barra Verde 240g",
    price: 3.20,
    costPrice: 2.10,
    category: "Limpieza",
    unit: "barra",
    stock: 40,
    stockMin: 8,
    stockMax: 60,
    description: "Jabón de ropa en barra, poder desengrasante.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20490950/20201620.jpg",
    barcode: "7751271004003",
  },
  {
    name: "Papel Higiénico Suave Triple Hoja x4",
    price: 9.90,
    costPrice: 7.00,
    category: "Limpieza",
    unit: "paquete",
    stock: 30,
    stockMin: 6,
    stockMax: 45,
    description: "Papel higiénico triple hoja, extra suave.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588300/20201630.jpg",
    barcode: "7751271004004",
  },
  {
    name: "Lavavajillas Ayudín Limón 900g",
    price: 7.50,
    costPrice: 5.20,
    category: "Limpieza",
    unit: "pote",
    stock: 22,
    stockMin: 4,
    stockMax: 35,
    description: "Crema lavavajillas con poder desengrasante y aroma limón.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103600/20201640.jpg",
    barcode: "7751271004005",
  },
  {
    name: "Insecticida Sapolio Mata Moscas 360ml",
    price: 11.90,
    costPrice: 8.50,
    category: "Limpieza",
    unit: "spray",
    stock: 18,
    stockMin: 3,
    stockMax: 30,
    description: "Insecticida en aerosol, mata moscas y zancudos al instante.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20491000/20211070.jpg",
    barcode: "7751271004006",
  },

  // ═══════════════════════════════════════
  // FRUTAS Y VERDURAS (7 productos)
  // ═══════════════════════════════════════
  {
    name: "Papa Amarilla Tumbay 1kg",
    price: 5.90,
    costPrice: 3.50,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 40,
    stockMin: 8,
    stockMax: 60,
    description: "Papa amarilla nativa peruana, ideal para causa y puré.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603200/20201700.jpg",
    barcode: "7751271005001",
    badge: "Fresco",
  },
  {
    name: "Cebolla Roja 1kg",
    price: 3.50,
    costPrice: 2.00,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 50,
    stockMin: 10,
    stockMax: 70,
    description: "Cebolla roja fresca, base de la cocina criolla peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603250/20201710.jpg",
    barcode: "7751271005002",
  },
  {
    name: "Limón Sutil 1kg",
    price: 5.50,
    costPrice: 3.00,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 35,
    stockMin: 8,
    stockMax: 50,
    description: "Limón sutil peruano, esencial para ceviche y limonada.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603300/20201720.jpg",
    barcode: "7751271005003",
    badge: "Para Ceviche",
  },
  {
    name: "Tomate Italiano 1kg",
    price: 4.50,
    costPrice: 2.50,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 35,
    stockMin: 8,
    stockMax: 50,
    description: "Tomate fresco, ideal para ensaladas y guisos.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603350/20201730.jpg",
    barcode: "7751271005004",
  },
  {
    name: "Palta Fuerte 1kg",
    price: 8.90,
    costPrice: 5.50,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 20,
    stockMin: 4,
    stockMax: 30,
    description: "Palta fuerte peruana, cremosa y perfecta para guacamole.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603400/20201740.jpg",
    barcode: "7751271005005",
  },
  {
    name: "Plátano de Seda 1kg",
    price: 2.90,
    costPrice: 1.60,
    category: "Frutas y Verduras",
    unit: "kg",
    stock: 45,
    stockMin: 10,
    stockMax: 60,
    description: "Plátano de seda fresco de la selva peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603450/20201750.jpg",
    barcode: "7751271005006",
  },
  {
    name: "Ají Amarillo Fresco 250g",
    price: 2.50,
    costPrice: 1.30,
    category: "Frutas y Verduras",
    unit: "bolsa",
    stock: 30,
    stockMin: 5,
    stockMax: 45,
    description: "Ají amarillo fresco, ingrediente estrella de la gastronomía peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/21603500/20211080.jpg",
    barcode: "7751271005007",
    badge: "Peruano",
  },

  // ═══════════════════════════════════════
  // CARNES Y PROTEÍNAS (4 productos)
  // ═══════════════════════════════════════
  {
    name: "Pollo Entero Sin Menudencia 1kg",
    price: 11.90,
    costPrice: 8.80,
    category: "Carnes",
    unit: "kg",
    stock: 15,
    stockMin: 3,
    stockMax: 25,
    description: "Pollo fresco entero, criado en granjas peruanas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103700/20201800.jpg",
    barcode: "7751271006001",
    badge: "Fresco",
  },
  {
    name: "Carne de Res Bisteck 1kg",
    price: 29.90,
    costPrice: 23.00,
    category: "Carnes",
    unit: "kg",
    stock: 8,
    stockMin: 2,
    stockMax: 15,
    description: "Corte fino de res para bisteck, tierno y jugoso.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103750/20201810.jpg",
    barcode: "7751271006002",
  },
  {
    name: "Pescado Jurel Fresco 1kg",
    price: 12.90,
    costPrice: 8.50,
    category: "Carnes",
    unit: "kg",
    stock: 10,
    stockMin: 2,
    stockMax: 18,
    description: "Jurel fresco del mar peruano, rico en omega 3.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103800/20201820.jpg",
    barcode: "7751271006003",
  },
  {
    name: "Chorizo Parrillero Braedt 500g",
    price: 16.90,
    costPrice: 12.00,
    category: "Carnes",
    unit: "paquete",
    stock: 12,
    stockMin: 3,
    stockMax: 20,
    description: "Chorizo parrillero premium, listo para la parrilla.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103850/20201830.jpg",
    barcode: "7751271006004",
  },

  // ═══════════════════════════════════════
  // SNACKS Y GOLOSINAS (4 productos)
  // ═══════════════════════════════════════
  {
    name: "Chocolate Sublime Clásico 30g",
    price: 2.50,
    costPrice: 1.70,
    category: "Snacks",
    unit: "unidad",
    stock: 100,
    stockMin: 20,
    stockMax: 150,
    description: "El chocolate más querido del Perú, con maní.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588400/20201900.jpg",
    barcode: "7751271007001",
    badge: "Popular",
  },
  {
    name: "Galletas Casino Fresa 6 Pack",
    price: 3.50,
    costPrice: 2.40,
    category: "Snacks",
    unit: "paquete",
    stock: 50,
    stockMin: 10,
    stockMax: 70,
    description: "Galletas rellenas sabor fresa, marca icónica peruana.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22103900/20201910.jpg",
    barcode: "7751271007002",
  },
  {
    name: "Chifles Karinto 150g",
    price: 4.50,
    costPrice: 3.00,
    category: "Snacks",
    unit: "bolsa",
    stock: 30,
    stockMin: 6,
    stockMax: 45,
    description: "Chifles de plátano crocantes, snack típico peruano.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20491050/20211090.jpg",
    barcode: "7751271007003",
    badge: "Peruano",
  },
  {
    name: "King Kong Lambayeque Manjar 450g",
    price: 15.90,
    costPrice: 11.00,
    category: "Snacks",
    unit: "unidad",
    stock: 12,
    stockMin: 3,
    stockMax: 20,
    description: "Dulce tradicional lambayecano relleno de manjar blanco.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/20491100/20211095.jpg",
    barcode: "7751271007004",
    badge: "Tradicional",
  },

  // ═══════════════════════════════════════
  // CUIDADO PERSONAL (3 productos)
  // ═══════════════════════════════════════
  {
    name: "Jabón Neko Antibacterial 125g",
    price: 3.90,
    costPrice: 2.60,
    category: "Cuidado Personal",
    unit: "barra",
    stock: 40,
    stockMin: 8,
    stockMax: 60,
    description: "Jabón antibacterial, protección para toda la familia.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22104000/20202000.jpg",
    barcode: "7751271008001",
  },
  {
    name: "Pasta Dental Kolynos 100ml",
    price: 5.50,
    costPrice: 3.80,
    category: "Cuidado Personal",
    unit: "tubo",
    stock: 25,
    stockMin: 5,
    stockMax: 40,
    description: "Pasta dental con flúor, protección anticaries.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22104050/20202010.jpg",
    barcode: "7751271008002",
  },
  {
    name: "Shampoo Savital Sábila 530ml",
    price: 12.90,
    costPrice: 9.00,
    category: "Cuidado Personal",
    unit: "botella",
    stock: 18,
    stockMin: 4,
    stockMax: 30,
    description: "Shampoo con extracto de sábila, cabello fuerte y brillante.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/22104100/20202020.jpg",
    barcode: "7751271008003",
  },

  // ═══════════════════════════════════════
  // PANADERÍA (2 productos)
  // ═══════════════════════════════════════
  {
    name: "Pan de Molde Bimbo Blanco 500g",
    price: 7.90,
    costPrice: 5.50,
    category: "Panadería",
    unit: "paquete",
    stock: 20,
    stockMin: 5,
    stockMax: 35,
    description: "Pan de molde blanco, suave y esponjoso para sándwiches.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/23588500/20202100.jpg",
    barcode: "7751271009001",
  },
  {
    name: "Panetón D'Onofrio 900g",
    price: 24.90,
    costPrice: 18.00,
    category: "Panadería",
    unit: "caja",
    stock: 15,
    stockMin: 3,
    stockMax: 25,
    description: "El panetón más tradicional del Perú, con frutas confitadas.",
    image: "https://plazavea.vteximg.com.br/arquivos/ids/25207800/20202110.jpg",
    barcode: "7751271009002",
    badge: "Clásico",
  },
];

export async function POST(req: NextRequest) {
  const auth = await requireAdmin(req, ["admin"]);
  if (auth instanceof NextResponse) return auth;

  // SEGURIDAD: Solo tenant "main"
  if (auth.tenantId !== "main") {
    return NextResponse.json(
      { error: "Este endpoint solo funciona para la tienda principal (main)" },
      { status: 403 }
    );
  }

  try {
    // Verificar cuántos productos ya existen en "main"
    const existingCount = await prisma.product.count({
      where: { tenantId: "main", deletedAt: null },
    });

    let created = 0;
    let skipped = 0;

    for (const p of PRODUCTOS_PERU) {
      // Evitar duplicados por nombre + tenant
      const exists = await prisma.product.findFirst({
        where: { tenantId: "main", name: p.name, deletedAt: null },
      });

      if (exists) {
        skipped++;
        continue;
      }

      await prisma.product.create({
        data: {
          tenantId: "main",
          name: p.name,
          category: p.category,
          price: p.price,
          costPrice: p.costPrice,
          unit: p.unit,
          stock: p.stock,
          stockMin: p.stockMin,
          stockMax: p.stockMax,
          description: p.description,
          image: p.image,
          barcode: p.barcode,
          badge: p.badge ?? null,
          active: true,
        },
      });
      created++;
    }

    return NextResponse.json({
      created,
      skipped,
      totalBefore: existingCount,
      totalAfter: existingCount + created,
      message: `✅ ${created} productos peruanos creados en tienda "main". ${skipped} omitidos (ya existían).`,
    });
  } catch (e) {
    logger.error("[seed-peru-products] POST error", { error: (e as Error).message, tenantId: auth.tenantId });
    return NextResponse.json(
      { error: "Error al crear productos peruanos" },
      { status: 500 }
    );
  }
}
