"use client";
import { useState, useMemo, useEffect } from "react";
import { Bell, Plus, Check, Trash2, Clock, AlertTriangle, Package, DollarSign, Calendar, X, CheckCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";

/* ── types ──────────────────────────────────────────────────── */
type ReminderType = "pago" | "inventario" | "tarea" | "vencimiento" | "cliente" | "general";
type ReminderPriority = "alta" | "media" | "baja";
type ReminderStatus = "pendiente" | "completado" | "vencido";

type Reminder = {
  id: string;
  title: string;
  description: string;
  type: ReminderType;
  priority: ReminderPriority;
  status: ReminderStatus;
  dueDate: string;
  createdAt: string;
  autoGenerated: boolean;
};

/* ── config ─────────────────────────────────────────────────── */
const TYPE_CONFIG: Record<ReminderType, { label: string; icon: typeof Bell; color: string }> = {
  pago:        { label: "Pago", icon: DollarSign, color: "text-emerald-600" },
  inventario:  { label: "Inventario", icon: Package, color: "text-blue-600" },
  tarea:       { label: "Tarea", icon: CheckCircle, color: "text-purple-600" },
  vencimiento: { label: "Vencimiento", icon: AlertTriangle, color: "text-red-600" },
  cliente:     { label: "Cliente", icon: Bell, color: "text-amber-600" },
  general:     { label: "General", icon: Clock, color: "text-gray-600" },
};

const PRIORITY_CONFIG: Record<ReminderPriority, { label: string; color: string; dot: string }> = {
  alta:  { label: "Alta",  color: "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400",    dot: "bg-red-500" },
  media: { label: "Media", color: "bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400", dot: "bg-amber-500" },
  baja:  { label: "Baja",  color: "bg-gray-100 dark:bg-surface text-gray-600 dark:text-muted",        dot: "bg-gray-400" },
};

/* ── seed data ──────────────────────────────────────────────── */
const INITIAL_REMINDERS: Reminder[] = [];

/* ── component ──────────────────────────────────────────────── */
export default function SmartRemindersTab() {
  const [reminders, setReminders] = useState<Reminder[]>(INITIAL_REMINDERS);
  const [typeFilter, setTypeFilter] = useState<"all" | ReminderType>("all");
  const [statusFilter, setStatusFilter] = useState<"all" | ReminderStatus>("all");
  const [showNew, setShowNew] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newType, setNewType] = useState<ReminderType>("tarea");
  const [newPriority, setNewPriority] = useState<ReminderPriority>("media");
  const [newDue, setNewDue] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/reminders")
      .then(r => r.json())
      .then(d => setReminders(Array.isArray(d) ? d : []))
      .finally(() => setLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return reminders.filter(r => {
      if (typeFilter !== "all" && r.type !== typeFilter) return false;
      if (statusFilter !== "all" && r.status !== statusFilter) return false;
      return true;
    }).sort((a, b) => {
      if (a.status === "completado" && b.status !== "completado") return 1;
      if (a.status !== "completado" && b.status === "completado") return -1;
      const priorityOrder = { alta: 0, media: 1, baja: 2 };
      if (priorityOrder[a.priority] !== priorityOrder[b.priority]) return priorityOrder[a.priority] - priorityOrder[b.priority];
      return a.dueDate.localeCompare(b.dueDate);
    });
  }, [reminders, typeFilter, statusFilter]);

  const stats = useMemo(() => ({
    total: reminders.length,
    pending: reminders.filter(r => r.status === "pendiente").length,
    overdue: reminders.filter(r => r.status === "vencido").length,
    completed: reminders.filter(r => r.status === "completado").length,
    autoGenerated: reminders.filter(r => r.autoGenerated).length,
    highPriority: reminders.filter(r => r.priority === "alta" && r.status === "pendiente").length,
  }), [reminders]);

  const handleComplete = async (id: string) => {
    const r = reminders.find(x => x.id === id);
    if (!r) return;
    const nextStatus = r.status === "completado" ? "pendiente" : "completado";
    setReminders(prev => prev.map(x => x.id === id ? { ...x, status: nextStatus } : x));
    try {
      await fetch(`/api/reminders?id=${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus }) });
      if (nextStatus === "completado") toast.success("Recordatorio completado ✓");
    } catch { toast.error("Error al actualizar el recordatorio"); }
  };

  const handleDelete = async (id: string) => {
    setReminders(prev => prev.filter(r => r.id !== id));
    try {
      await fetch(`/api/reminders?id=${id}`, { method: "DELETE" });
      toast.success("Recordatorio eliminado");
    } catch { toast.error("Error al eliminar el recordatorio"); }
  };

  const handleAdd = async () => {
    if (!newTitle.trim() || !newDue) return;
    try {
      const res = await fetch("/api/reminders", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: newTitle.trim(),
          description: newDesc.trim(),
          type: newType,
          priority: newPriority,
          dueDate: new Date(newDue).toISOString(),
          autoGenerated: false,
        }),
      });
      if (res.ok) {
        const created = await res.json();
        setReminders(prev => [...prev, created]);
        toast.success("Recordatorio creado");
      } else { toast.error("Error al crear el recordatorio"); }
    } catch { toast.error("Error al crear el recordatorio"); }
    setNewTitle(""); setNewDesc(""); setNewDue(""); setShowNew(false);
  };

  const getDaysText = (dueDate: string) => {
    const diff = Math.ceil((new Date(dueDate).getTime() - new Date().getTime()) / 86400000);
    if (diff < 0) return `Hace ${Math.abs(diff)} días`;
    if (diff === 0) return "Hoy";
    if (diff === 1) return "Mañana";
    return `En ${diff} días`;
  };

  return (
    <div className="space-y-3 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 sm:gap-4">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-gray-900 dark:text-foreground">Recordatorios Inteligentes</h2>
          <p className="text-sm text-gray-500 dark:text-muted mt-1">Alertas automáticas y manuales para pagos, inventario, tareas y más</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button onClick={() => setShowNew(true)} className="flex flex-wrap items-center gap-2 px-2 sm:px-4 py-1.5 sm:py-2.5 rounded-xl bg-primary text-white text-sm font-bold hover:bg-primary/90 transition-colors shadow-md shadow-primary/20">
            <Plus className="h-4 w-4" /> Nuevo recordatorio
          </button>
        </div>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-4">
        <div className="bg-white dark:bg-card rounded-2xl border border-gray-200 dark:border-card-border p-4 shadow-sm">
          <p className="text-xs text-gray-500 dark:text-muted font-semibold">Pendientes</p>
          <p className="text-xl sm:text-2xl font-extrabold text-amber-600 mt-1">{stats.pending}</p>
        </div>
        <div className="bg-red-50 dark:bg-red-950/20 rounded-2xl border border-red-200 dark:border-red-800 p-4 shadow-sm">
          <p className="text-xs text-red-600 dark:text-red-400 font-semibold">Prioridad alta</p>
          <p className="text-xl sm:text-2xl font-extrabold text-red-700 dark:text-red-400 mt-1">{stats.highPriority}</p>
        </div>
        <div className="bg-emerald-50 dark:bg-emerald-950/20 rounded-2xl border border-emerald-200 dark:border-emerald-800 p-4 shadow-sm">
          <p className="text-xs text-emerald-600 dark:text-emerald-400 font-semibold">Completados</p>
          <p className="text-xl sm:text-2xl font-extrabold text-emerald-700 dark:text-emerald-400 mt-1">{stats.completed}</p>
        </div>
        <div className="bg-white dark:bg-card rounded-2xl border border-gray-200 dark:border-card-border p-4 shadow-sm">
          <p className="text-xs text-gray-500 dark:text-muted font-semibold">Auto-generados</p>
          <p className="text-xl sm:text-2xl font-extrabold text-blue-600 mt-1">{stats.autoGenerated}</p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <select value={typeFilter} onChange={e => setTypeFilter(e.target.value as typeof typeFilter)} className="px-3 py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-sm outline-none focus:border-primary">
          <option value="all">Todos los tipos</option>
          {Object.entries(TYPE_CONFIG).map(([key, cfg]) => <option key={key} value={key}>{cfg.label}</option>)}
        </select>
        <div className="flex rounded-xl border border-gray-200 dark:border-card-border overflow-hidden">
          {([["all", "Todos"], ["pendiente", "Pendiente"], ["completado", "Hecho"], ["vencido", "Vencido"]] as const).map(([val, lbl]) => (
            <button key={val} onClick={() => setStatusFilter(val)} className={cn("px-3 py-2 text-sm font-semibold transition-colors", statusFilter === val ? "bg-primary text-white" : "text-gray-600 dark:text-muted hover:bg-gray-50 dark:hover:bg-surface")}>{lbl}</button>
          ))}
        </div>
      </div>

      {/* Reminders list */}
      {loading ? (
        <div className="space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="bg-white dark:bg-card rounded-2xl border border-gray-200 dark:border-card-border p-4 animate-pulse">
              <div className="flex flex-wrap items-center gap-3">
                <div className="h-8 w-8 rounded-full bg-gray-200 dark:bg-surface shrink-0" />
                <div className="flex-1 space-y-2">
                  <div className="h-3.5 bg-gray-200 dark:bg-surface rounded-full w-2/3" />
                  <div className="h-3 bg-gray-100 dark:bg-surface/60 rounded-full w-1/2" />
                </div>
                <div className="h-5 w-20 bg-gray-100 dark:bg-surface/60 rounded-full" />
              </div>
            </div>
          ))}
        </div>
      ) : (
      <div className="space-y-3">
        {filtered.map(r => {
          const typeCfg = TYPE_CONFIG[r.type];
          const priCfg = PRIORITY_CONFIG[r.priority];
          const TypeIcon = typeCfg.icon;
          const isCompleted = r.status === "completado";
          return (
            <div key={r.id} className={cn("bg-white dark:bg-card rounded-2xl border border-gray-200 dark:border-card-border p-4 shadow-sm flex items-start gap-2 sm:gap-4 transition-all", isCompleted && "opacity-60")}>
              <button onClick={() => handleComplete(r.id)} className={cn("mt-0.5 w-6 h-6 rounded-full border-2 flex items-center justify-center shrink-0 transition-colors", isCompleted ? "bg-emerald-500 border-emerald-500" : "border-gray-300 dark:border-card-border hover:border-primary")}>
                {isCompleted && <Check className="h-3.5 w-3.5 text-white" />}
              </button>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap mb-1">
                  <h3 className={cn("font-bold text-sm", isCompleted ? "line-through text-gray-400 dark:text-muted" : "text-gray-900 dark:text-foreground")}>{r.title}</h3>
                  {r.autoGenerated && <span className="px-1.5 py-0.5 rounded bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 text-[10px] font-bold">AUTO</span>}
                </div>
                <p className="text-xs text-gray-500 dark:text-muted mb-2 line-clamp-2">{r.description}</p>
                <div className="flex items-center gap-3 flex-wrap">
                  <span className={cn("inline-flex items-center gap-1 text-xs font-semibold", typeCfg.color)}>
                    <TypeIcon className="h-3 w-3" /> {typeCfg.label}
                  </span>
                  <span className={cn("inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-bold", priCfg.color)}><span className={cn("w-1.5 h-1.5 rounded-full", priCfg.dot)} /> {priCfg.label}</span>
                  <span className="text-xs text-gray-400 dark:text-muted flex items-center gap-1"><Calendar className="h-3 w-3" /> {r.dueDate}</span>
                  <span className={cn("text-xs font-semibold", r.dueDate < new Date().toISOString().slice(0, 10) && r.status !== "completado" ? "text-red-500" : "text-gray-400 dark:text-muted")}>{getDaysText(r.dueDate)}</span>
                </div>
              </div>
              <button onClick={() => handleDelete(r.id)} className="p-1.5 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors shrink-0">
                <Trash2 className="h-4 w-4" />
              </button>
            </div>
          );
        })}
      </div>
      )}

      {!loading && filtered.length === 0 && (
        <div className="text-center py-12"><Bell className="h-12 w-12 text-gray-300 dark:text-muted mx-auto mb-3" /><p className="text-gray-400 dark:text-muted font-semibold">No hay recordatorios{statusFilter !== "all" ? " en este estado" : ""}</p></div>
      )}

      {/* New modal */}
      {showNew && (
        <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={() => setShowNew(false)}>
          <div className="bg-white dark:bg-card rounded-2xl shadow-xl w-full max-w-md" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-3 sm:px-6 py-4 border-b border-gray-100 dark:border-card-border">
              <h3 className="font-extrabold text-gray-900 dark:text-foreground">Nuevo recordatorio</h3>
              <button onClick={() => setShowNew(false)} className="p-1.5 rounded-lg text-gray-400 hover:bg-gray-100 dark:hover:bg-accent"><X className="h-5 w-5" /></button>
            </div>
            <div className="px-3 sm:px-6 py-5 space-y-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-foreground mb-1">Título</label>
                <input type="text" value={newTitle} onChange={e => setNewTitle(e.target.value)} placeholder="¿Qué necesitas recordar?" className="w-full px-2 sm:px-4 py-1.5 sm:py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-gray-900 dark:text-foreground text-sm outline-none focus:border-primary" autoFocus />
              </div>
              <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-foreground mb-1">Descripción</label>
                <textarea value={newDesc} onChange={e => setNewDesc(e.target.value)} placeholder="Detalles opcionales..." rows={2} className="w-full px-2 sm:px-4 py-1.5 sm:py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-gray-900 dark:text-foreground text-sm outline-none focus:border-primary resize-none" />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-foreground mb-1">Tipo</label>
                  <select value={newType} onChange={e => setNewType(e.target.value as ReminderType)} className="w-full px-2 py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-xs outline-none focus:border-primary">
                    {Object.entries(TYPE_CONFIG).map(([key, cfg]) => <option key={key} value={key}>{cfg.label}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-foreground mb-1">Prioridad</label>
                  <select value={newPriority} onChange={e => setNewPriority(e.target.value as ReminderPriority)} className="w-full px-2 py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-xs outline-none focus:border-primary">
                    <option value="alta">Alta</option><option value="media">Media</option><option value="baja">Baja</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-foreground mb-1">Fecha límite</label>
                  <input type="date" value={newDue} onChange={e => setNewDue(e.target.value)} className="w-full px-2 py-2.5 rounded-xl border-2 border-gray-200 dark:border-card-border bg-white dark:bg-surface text-xs outline-none focus:border-primary" />
                </div>
              </div>
              <div className="flex flex-wrap justify-end gap-3 pt-2">
                <button onClick={() => setShowNew(false)} className="px-2 sm:px-4 py-1.5 sm:py-2.5 rounded-xl text-sm font-semibold text-gray-600 dark:text-muted hover:bg-gray-100 dark:hover:bg-accent">Cancelar</button>
                <button onClick={handleAdd} disabled={!newTitle.trim() || !newDue} className="px-5 py-2.5 rounded-xl bg-primary text-white text-sm font-bold hover:bg-primary/90 disabled:opacity-50">Crear</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
