import type { LucideIcon } from "lucide-react";
import type { Product } from "@/types/erp";

export type SmartInsight = {
  priority: number;
  icon: LucideIcon;
  title: string;
  desc: string;
  type: "danger" | "warning" | "success" | "info";
};

export interface DashboardStats {
  ventas: number;
  costo: number;
  utilidad: number;
  margen: number;
  tickets: number;
  ticketProm: number;
  uds: number;
  clientesAtendidos: number;
  cancelados: number;
  stockVal: number;
  stockCritico: Product[];
  agotados: Product[];
  sinMov: Product[];
  catSales: { cat: string; total: number; label: string; color: string }[];
  payments: { method: string; total: number; label: string; color: string }[];
  payTotal: number;
  daily: [string, number][];
  maxDaily: number;
  hourMap: Map<string, number>;
  maxHeat: number;
  topRev: { id: number; name: string; units: number; revenue: number; profit: number }[];
  topProfit: { id: number; name: string; units: number; revenue: number; profit: number }[];
  topUnits: { id: number; name: string; units: number; revenue: number; profit: number }[];
  recent: { id: string; customer: { name: string; phone?: string; location: string; reference: string }; items: { id: number; name: string; price: number; quantity: number; unit: string; image: string }[]; total: number; status: string; paymentMethod?: string; createdAt: string; updatedAt: string; notes?: string; adminNote?: string; statusHistory?: { status: string; at: string }[] }[];
  supPurchases: { name: string; total: number }[];
  totalPurch: number;
  debt: number;
  overdue: { id: string; supplierId: string; supplierName: string; amount: number; paidAmount: number; status: string; dueDate: string }[];
  pending: { id: string; supplierId: string; supplierName: string; amount: number; paidAmount: number; status: string; dueDate: string }[];
  alerts: { type: "danger" | "warning" | "info"; msg: string }[];
  insights: SmartInsight[];
  avgRating: number;
  totalCustomers: number;
  totalSuppliers: number;
  activeProducts: number;
  dVentas: number | null;
  dUtilidad: number | null;
  dTickets: number | null;
  dTicketProm: number | null;
  dMargen: number | null;
  dUds: number | null;
  dClientes: number | null;
  dCancelados: number | null;
  pendingOrdersCount: number;
  completedOrdersCount: number;
  conversionRate: number;
  dailyProfit: number[];
  funnelData: { label: string; count: number; color: string }[];
  newCust: number;
  returningCust: number;
  trendSlope: number;
  trendIntercept: number;
  forecast7: { day: string; value: number }[];
  wowGrowth: number | null;
  movingAvg7: number[];
  conversionFunnelData: { label: string; count: number; pct: number; color: string }[];
  overallConversionRate: number;
  basketAbandonmentRate: number;
  checkoutCompletionRate: number;
  paretoChartData: { id: number; name: string; units: number; revenue: number; profit: number; cumulativePct: number; abcClass: "A" | "B" | "C"; revenuePct: number }[];
  classA: { id: number; name: string; revenue: number }[];
  classB: { id: number; name: string; revenue: number }[];
  classC: { id: number; name: string; revenue: number }[];
  stockProjections: { id: number; name: string; stock?: number; stockMin?: number; soldLast30d: number; dailyRate: number; daysRemaining: number; needsReorder: boolean; criticalReorder: boolean; suggestedOrderQty: number; category: string; price: number; costPrice?: number; active: boolean }[];
  criticalStock: { id: number; name: string; stock?: number; daysRemaining: number; suggestedOrderQty: number; dailyRate: number }[];
  needsReorderSoon: { id: number; name: string; stock?: number; daysRemaining: number; suggestedOrderQty: number; dailyRate: number }[];
  atRiskClients: { phone: string; name: string; totalSpent: number; orderCount: number; lastOrderDate: string; daysSinceLastOrder: number }[];
  decliningClients: { phone: string; name: string; totalSpent: number; orderCount: number; lastOrderDate: string; daysSinceLastOrder: number }[];
  productAffinities: { a: string; b: string; count: number }[];
  yesterdayRevenue: number;
  yesterdayTickets: number;
  todayRevenue: number;
  briefingPriorities: string[];
  cashFlowForecast: { day: string; dayLabel: string; estRevenue: number; estExpense: number; net: number }[];
  forecastTotalRev: number;
  forecastTotalExp: number;
  sparklineRevenue: number[];
  sparklineOrders: number[];
  sparklineAvgTicket: number[];
  sparklineProfit: number[];
  cohortData: { cohortMonth: string; month0: number; month1: number; month2: number; month3: number; month4: number; month5plus: number }[];
  retentionMetrics: { day1: number; day7: number; day30: number };
  crossSellRecommendations: Map<number, { productId: number; confidence: number }[]>;
}
