/**
 * API /api/reminders – unit tests
 * Covers: auth failure, validation, GET (with overdue auto-mark), POST create, PATCH update, DELETE
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { NextRequest, NextResponse } from "next/server";

vi.mock("server-only", () => ({}));

const { mockRequireAdmin } = vi.hoisted(() => ({
  mockRequireAdmin: vi.fn(),
}));
vi.mock("@/lib/require-admin", () => ({ requireAdmin: mockRequireAdmin }));

const { mockFindMany, mockCreate, mockFindFirst, mockUpdate, mockUpdateMany, mockDelete } = vi.hoisted(() => ({
  mockFindMany: vi.fn(),
  mockCreate: vi.fn(),
  mockFindFirst: vi.fn(),
  mockUpdate: vi.fn(),
  mockUpdateMany: vi.fn(),
  mockDelete: vi.fn(),
}));
vi.mock("@/lib/prisma", () => ({
  prisma: {
    reminder: {
      findMany: mockFindMany,
      create: mockCreate,
      findFirst: mockFindFirst,
      update: mockUpdate,
      updateMany: mockUpdateMany,
      delete: mockDelete,
    },
  },
}));

import { GET, POST, PATCH, DELETE } from "@/app/api/reminders/route";

const AUTH = { tenantId: "main", role: "admin", username: "test" };
const UNAUTH = NextResponse.json({ error: "unauthorized" }, { status: 401 });

function makeReq(method: string, url: string, body?: unknown): NextRequest {
  return new NextRequest(url, {
    method,
    ...(body !== undefined
      ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }
      : {}),
  });
}

const NOW = new Date("2026-01-01T00:00:00Z");
const FUTURE_DATE = "2027-06-15T00:00:00.000Z";
const BASE_REMINDER = {
  id: "r1", tenantId: "main", title: "Pagar proveedor",
  description: "", type: "pago", priority: "alta",
  status: "pendiente", dueDate: new Date(FUTURE_DATE),
  autoGenerated: false, createdAt: NOW, updatedAt: NOW,
};
const VALID_BODY = { title: "Pagar proveedor", type: "pago", dueDate: FUTURE_DATE };

// ── GET ──────────────────────────────────────────────────────────────────────

describe("GET /api/reminders", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns 401 when unauthenticated", async () => {
    mockRequireAdmin.mockResolvedValue(UNAUTH);
    const res = await GET(makeReq("GET", "https://host/api/reminders"));
    expect(res.status).toBe(401);
  });

  it("auto-marks overdue reminders and returns list", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockUpdateMany.mockResolvedValue({ count: 1 });
    mockFindMany.mockResolvedValue([BASE_REMINDER]);
    const res = await GET(makeReq("GET", "https://host/api/reminders"));
    expect(res.status).toBe(200);
    expect(mockUpdateMany).toHaveBeenCalledOnce();
    const body = await res.json();
    expect(body[0].title).toBe("Pagar proveedor");
    expect(body[0].dueDate).toBe("2027-06-15"); // formatted as date string
  });

  it("returns empty array when no reminders", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockUpdateMany.mockResolvedValue({ count: 0 });
    mockFindMany.mockResolvedValue([]);
    const res = await GET(makeReq("GET", "https://host/api/reminders"));
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual([]);
  });
});

// ── POST ─────────────────────────────────────────────────────────────────────

describe("POST /api/reminders", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns 401 when unauthenticated", async () => {
    mockRequireAdmin.mockResolvedValue(UNAUTH);
    const res = await POST(makeReq("POST", "https://host/api/reminders", VALID_BODY));
    expect(res.status).toBe(401);
  });

  it("returns 400 on missing title", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    const res = await POST(makeReq("POST", "https://host/api/reminders", { type: "pago", dueDate: FUTURE_DATE }));
    expect(res.status).toBe(400);
  });

  it("returns 400 on invalid type", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    const res = await POST(makeReq("POST", "https://host/api/reminders", { ...VALID_BODY, type: "inexistente" }));
    expect(res.status).toBe(400);
  });

  it("returns 400 on invalid dueDate (not ISO datetime)", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    const res = await POST(makeReq("POST", "https://host/api/reminders", { ...VALID_BODY, dueDate: "15/06/2027" }));
    expect(res.status).toBe(400);
  });

  it("creates reminder and returns 201", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockCreate.mockResolvedValue(BASE_REMINDER);
    const res = await POST(makeReq("POST", "https://host/api/reminders", VALID_BODY));
    expect(res.status).toBe(201);
    const body = await res.json();
    expect(body.title).toBe("Pagar proveedor");
    expect(body.status).toBe("pendiente");
  });
});

// ── PATCH ────────────────────────────────────────────────────────────────────

describe("PATCH /api/reminders", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns 400 when id is missing", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    const res = await PATCH(makeReq("PATCH", "https://host/api/reminders", { status: "completado" }));
    expect(res.status).toBe(400);
  });

  it("returns 404 when reminder not found", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockFindFirst.mockResolvedValue(null);
    const res = await PATCH(makeReq("PATCH", "https://host/api/reminders?id=x", { status: "completado" }));
    expect(res.status).toBe(404);
  });

  it("marks reminder as completado", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockFindFirst.mockResolvedValue(BASE_REMINDER);
    mockUpdate.mockResolvedValue({ ...BASE_REMINDER, status: "completado" });
    const res = await PATCH(makeReq("PATCH", "https://host/api/reminders?id=r1", { status: "completado" }));
    expect(res.status).toBe(200);
    expect((await res.json()).status).toBe("completado");
  });
});

// ── DELETE ───────────────────────────────────────────────────────────────────

describe("DELETE /api/reminders", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns 400 when id is missing", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    const res = await DELETE(makeReq("DELETE", "https://host/api/reminders"));
    expect(res.status).toBe(400);
  });

  it("returns 404 when reminder not found", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockFindFirst.mockResolvedValue(null);
    const res = await DELETE(makeReq("DELETE", "https://host/api/reminders?id=x"));
    expect(res.status).toBe(404);
  });

  it("deletes and returns { ok: true }", async () => {
    mockRequireAdmin.mockResolvedValue(AUTH);
    mockFindFirst.mockResolvedValue(BASE_REMINDER);
    mockDelete.mockResolvedValue({});
    const res = await DELETE(makeReq("DELETE", "https://host/api/reminders?id=r1"));
    expect(res.status).toBe(200);
    expect((await res.json()).ok).toBe(true);
  });
});
